import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {ROOT} from './config.mjs';
const T=await import(pathToFileURL(path.join(ROOT,'node_modules/three/build/three.module.js')));
const plain=b=>b.isEmpty()?null:{min:b.min.toArray(),max:b.max.toArray()};
const matrixFor=(p=[0,0,0],r=[0,0,0,1],s=[1,1,1])=>new T.Matrix4().compose(new T.Vector3(...p),new T.Quaternion(...r),new T.Vector3(...s));
function readAsset(id,file){
 const bytes=fs.readFileSync(path.isAbsolute(file)?file:path.join(ROOT,file)),jl=bytes.readUInt32LE(12),j=JSON.parse(bytes.toString('utf8',20,20+jl)),bin=28+jl,cache=new Map();
 function access(i){if(cache.has(i))return cache.get(i);const a=j.accessors[i],v=j.bufferViews[a.bufferView];if(a.sparse)throw Error('Sparse accessor unsupported');const n={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16}[a.type],sz={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4}[a.componentType],read={5120:'readInt8',5121:'readUInt8',5122:'readInt16LE',5123:'readUInt16LE',5125:'readUInt32LE',5126:'readFloatLE'}[a.componentType],div={5120:127,5121:255,5122:32767,5123:65535,5125:4294967295}[a.componentType],out=[];for(let k=0;k<a.count;k++){const row=[],o=bin+(v.byteOffset||0)+(a.byteOffset||0)+k*(v.byteStride||sz*n);for(let q=0;q<n;q++){let x=bytes[read](o+q*sz);if(a.normalized)x=Math.max(-1,x/div);row.push(x);}out.push(row);}cache.set(i,out);return out;}
 const parent=Array(j.nodes.length).fill(-1);j.nodes.forEach((n,i)=>(n.children||[]).forEach(c=>parent[c]=i));
 const under=(node,root)=>{for(let n=node;n>=0;n=parent[n])if(n===root)return true;return false;};
 const animated=new Set((j.animations||[]).flatMap(a=>a.channels.map(c=>c.target.node)));
 const sockets=j.nodes.map((n,i)=>({n,i})).filter(({n})=>n.extras?.kind==='weapon'||n.extras?.role==='weapon-mount');
 function poses(clips={},gear){
  const overrides=new Map();
  for(const [name,t] of Object.entries(clips)){const clip=j.animations.find(a=>a.name===name);if(!clip)throw Error('Missing clip '+name);const duration=Math.max(...clip.samplers.flatMap(s=>access(s.input).flat()));for(const c of clip.channels){const s=clip.samplers[c.sampler],times=access(s.input).flat(),values=access(s.output),time=t*duration;let k=0;while(k+1<times.length&&times[k+1]<=time)k++;const next=Math.min(k+1,times.length-1),mix=next===k?0:(time-times[k])/(times[next]-times[k]);if(!['LINEAR','STEP',undefined].includes(s.interpolation))throw Error('Unsupported interpolation '+s.interpolation);const f=s.interpolation==='STEP'?0:mix;const value=c.target.path==='rotation'?new T.Quaternion(...values[k]).slerp(new T.Quaternion(...values[next]),f).toArray():values[k].map((x,q)=>x+(values[next][q]-x)*f);if(!overrides.has(c.target.node))overrides.set(c.target.node,{});overrides.get(c.target.node)[c.target.path]=value;}}
  return overrides;
 }
 function frame(clips={},gear){const overrides=poses(clips,gear),world=[];function visit(i,p){const n=j.nodes[i],o=overrides.get(i)||{},m=n.matrix?new T.Matrix4().fromArray(n.matrix):matrixFor(o.translation||n.translation,o.rotation||n.rotation,o.scale||n.scale);world[i]=p.clone().multiply(m);for(const c of n.children||[])visit(c,world[i]);}for(const i of j.scenes[j.scene||0].nodes)visit(i,new T.Matrix4());const meshes=[],bounds=new T.Box3();let triangles=0;j.nodes.forEach((n,i)=>{if(n.mesh===undefined||n.name?.startsWith('AB_')||n.extras?.initiallyHidden)return;for(const p of j.meshes[n.mesh].primitives){if((p.mode??4)!==4)continue;const vertices=access(p.attributes.POSITION).map(q=>new T.Vector3(...q).applyMatrix4(world[i])),indices=p.indices!==undefined?access(p.indices).flat():vertices.map((_,k)=>k),b=new T.Box3().setFromPoints(vertices);bounds.union(b);triangles+=indices.length/3;meshes.push({name:n.name,node:i,vertices,indices,bounds:b,animated:[...animated].some(a=>under(i,a))});}});return {world,meshes,bounds,triangles};}
 return {id,file,j,access,parent,under,sockets,frame,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length};
}
function clip(poly,axis,edge,less){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=(a[axis]-edge)*(less?1:-1),db=(b[axis]-edge)*(less?1:-1),ia=da<=1e-9,ib=db<=1e-9;if(ia)out.push(a);if(ia!==ib){const t=da/(da-db);out.push(a.map((v,k)=>v+(b[k]-v)*t));}}return out;}
function clipBox(poly,min,max){for(let axis=0;axis<3;axis++){poly=clip(poly,axis,min[axis],false);if(!poly.length)return [];poly=clip(poly,axis,max[axis],true);if(!poly.length)return [];}return poly;}
function radialDistance(poly){let min=Infinity,sign=0,inside=true;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],dx=b[0]-a[0],dz=b[2]-a[2],den=dx*dx+dz*dz,t=den?Math.max(0,Math.min(1,-(a[0]*dx+a[2]*dz)/den)):0;min=Math.min(min,Math.hypot(a[0]+dx*t,a[2]+dz*t));const cross=dx*-a[2]-dz*-a[0];if(Math.abs(cross)>1e-9){const s=Math.sign(cross);if(sign&&s!==sign)inside=false;sign=s;}}return inside&&sign&&poly.length>=3?0:min;}
function envelope(frame,matrix,shape,asset,excludeRoot=-1,filter=()=>true){const inverse=matrix.clone().invert(),hits=[],allBounds=new T.Box3();for(const mesh of frame.meshes){if(asset.under(mesh.node,excludeRoot)||!filter(mesh))continue;const pts=mesh.vertices.map(v=>v.clone().applyMatrix4(inverse).toArray()),bounds=new T.Box3().setFromPoints(pts.map(p=>new T.Vector3(...p)));const min=shape.min??[-shape.radius,shape.low,-shape.radius],max=shape.max??[shape.radius,shape.high,shape.radius];if(!bounds.intersectsBox(new T.Box3(new T.Vector3(...min),new T.Vector3(...max))))continue;let count=0,closest=Infinity,witness=null;const clipped=new T.Box3();for(let k=0;k<mesh.indices.length;k+=3){let poly=mesh.indices.slice(k,k+3).map(i=>pts[i]);if(shape.radius!==undefined){poly=clip(poly,1,shape.low,false);if(poly.length)poly=clip(poly,1,shape.high,true);if(!poly.length)continue;const r=radialDistance(poly);if(r>shape.radius+1e-8)continue;closest=Math.min(closest,r);}else poly=clipBox(poly,min,max);if(!poly.length)continue;count++;for(const p of poly){clipped.expandByPoint(new T.Vector3(...p));allBounds.expandByPoint(new T.Vector3(...p));}witness??=poly[0];}if(count)hits.push({name:mesh.name,triangles:count,minimumRadius:closest===Infinity?undefined:closest,witnessLocal:witness,witnessShip:new T.Vector3(...witness).applyMatrix4(matrix).toArray(),clippedBounds:plain(clipped)});}return {triangles:hits.reduce((s,h)=>s+h.triangles,0),clippedBounds:plain(allBounds),hits};}
function ray(frame,start,direction,asset,excludeRoot=-1,far=30){const r=new T.Ray(start,direction),p=new T.Vector3();let best=null;for(const mesh of frame.meshes){if(asset.under(mesh.node,excludeRoot))continue;for(let k=0;k<mesh.indices.length;k+=3){const [a,b,c]=mesh.indices.slice(k,k+3).map(i=>mesh.vertices[i]);if(!r.intersectTriangle(a,b,c,false,p))continue;const distance=p.distanceTo(start);if(distance<1e-5||distance>far||best&&distance>=best.distance)continue;best={name:mesh.name,distance,point:p.toArray()};}}return best;}
function matrixInfo(m){return {origin:new T.Vector3().setFromMatrixPosition(m).toArray(),right:new T.Vector3(1,0,0).transformDirection(m).toArray(),normal:new T.Vector3(0,1,0).transformDirection(m).toArray(),bore:new T.Vector3(0,0,-1).transformDirection(m).toArray(),columnMajorMatrix:m.elements};}
export {readAsset,matrixFor,envelope,ray,matrixInfo,T};
