import { test, expect } from '@playwright/test';

test('orbital view, terrain streaming, landing, walking, boarding and launch',async({page})=>{
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error' && /THREE|shader|WebGL|TypeError|ReferenceError/i.test(message.text()))errors.push(message.text());});
  await page.goto('/');
  await page.waitForFunction(()=>window.starAgent?.state.ready,{},{timeout:60000});
  await page.evaluate(()=>window.starAgent.setRenderScale(.55));
  await page.waitForTimeout(3000);
  await page.screenshot({path:'test-results/orbit.png'});
  console.log('Orbit',await page.evaluate(()=>window.starAgent.state));
  expect(errors).toEqual([]);
  await page.getByRole('button',{name:'Controls H',exact:false}).click();
  await expect(page.locator('#help-dialog')).toBeVisible();
  await page.getByRole('button',{name:'Close controls'}).click();
  await page.locator('[data-destination="forest"]').click();
  await page.waitForFunction(()=>!window.starAgent.state.transiting,{},{timeout:20000});
  await page.screenshot({path:'test-results/forest-flight.png'});
  console.log('Forest',await page.evaluate(()=>window.starAgent.state));
  await page.keyboard.press('l');
  await page.waitForFunction(()=>window.starAgent.state.mode==='landed',{},{timeout:45000});
  await page.keyboard.press('f');
  await page.waitForFunction(()=>window.starAgent.state.mode==='walk');
  await page.waitForTimeout(2000);
  expect(await page.evaluate(()=>window.starAgent.state.insideShip)).toBe(true);
  await page.keyboard.down('KeyW');
  await page.waitForFunction(()=>window.starAgent.state.shipLocal[2]>2.2);
  await page.keyboard.up('KeyW');await page.keyboard.press('KeyX');
  await page.keyboard.press('KeyF');
  await page.waitForFunction(()=>window.starAgent.state.doorProgress===1);
  await page.keyboard.down('KeyW');
  await page.waitForFunction(()=>window.starAgent.state.shipLocal[2]>9);
  await page.keyboard.up('KeyW');await page.keyboard.press('KeyX');
  expect(await page.evaluate(()=>window.starAgent.state.insideShip)).toBe(false);
  await page.keyboard.press('Tab');
  await page.screenshot({path:'test-results/forest-walk.png'});
  await page.keyboard.press('KeyF');
  expect(await page.evaluate(()=>window.starAgent.state.mode)).toBe('walk');
  await page.keyboard.down('KeyS');
  await page.waitForFunction(()=>window.starAgent.state.shipLocal[2]<-1.4);
  await page.keyboard.up('KeyS');await page.keyboard.press('KeyX');
  await page.keyboard.press('KeyF');
  await page.waitForFunction(()=>window.starAgent.state.mode==='landed');
  await page.keyboard.press('l');
  await page.waitForFunction(()=>window.starAgent.state.mode==='flight');
  await page.keyboard.down('Space');await page.waitForTimeout(700);await page.keyboard.up('Space');
  expect(await page.evaluate(()=>window.starAgent.state.altitude)).toBeGreaterThan(10);
  await page.keyboard.press('Tab');
  await page.locator('[data-destination="polar"]').click();
  await page.waitForFunction(()=>!window.starAgent.state.transiting,{},{timeout:20000});
  await page.screenshot({path:'test-results/polar.png'});
  console.log('Polar',await page.evaluate(()=>window.starAgent.state));
  expect(errors).toEqual([]);
});
