import {test,expect} from '@playwright/test';import {mkdir,writeFile} from 'node:fs/promises';
const evidence='/home/cees/.cache/star-agent-sbu/evidence';
const frames=p=>p.evaluate(async()=>{for(let i=0;i<3;i++)await new Promise(r=>requestAnimationFrame(r));});
async function setup(page,hull='nomad',fixture=false){
 await mkdir(evidence,{recursive:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.addInitScript(()=>{window.cargoPad={id:'SBU standard Gamepad',mapping:'standard',index:0,connected:true,axes:[0,0,0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{value:()=>[window.cargoPad]});});await page.route('**/api/auth/session',r=>r.fulfill({json:{account:null}}));
 await page.goto(`/?dev=1&ship=${hull}&start=hangar&intro=0&debug&seed=7291${fixture?'&cargo-test=1':''}`);await page.waitForFunction(()=>window.starAgent?.state.ready&&window.starAgent.state.enabled&&window.starAgent.state.controller.armed&&!window.starAgent.state.transiting,undefined,{timeout:90000});
 const button=async(i,pressed)=>{await page.evaluate(({i,pressed})=>window.cargoPad.buttons[i]={pressed,value:+pressed},{i,pressed});await frames(page);};const tap=async i=>{await button(i,true);await button(i,false);};
 const choose=async key=>{for(let i=0;i<75;i++){if(await page.evaluate(k=>document.activeElement?.dataset.controllerKey===k,key)){await tap(0);return;}await tap(13);}throw Error(`Missing controller action ${key}`);};
 return {tap,button,choose,errors};
}
/** Read-only pose feedback, writes standard sticks only. */
async function walk(page,target,frame='ship',look=null){
 await page.evaluate(({target,frame,look})=>{window.cargoWalkDone=false;window.cargoWalkTimer=setInterval(()=>{const n=window.starAgent.navigation,pad=window.cargoPad,goal=frame==='world'?n.position.clone().fromArray(target):frame==='ship'?n.fromShipLocal(n.position.clone().fromArray(target)):n.station.toWorld(n.position.clone().fromArray(target),n.position.clone());const delta=goal.sub(n.position),up=frame==='world'?n.normal:n.station?.up??n.normal;delta.projectOnPlane(up);if(delta.length()<.2){pad.axes=[0,0,0,0];window.cargoWalkDone=true;clearInterval(window.cargoWalkTimer);return;}const local=delta.applyQuaternion(n.orientation.clone().invert());pad.axes[0]=Math.max(-1,Math.min(1,local.x));pad.axes[1]=Math.max(-1,Math.min(1,local.z));pad.axes[2]=0;pad.axes[3]=0;},30);},{target,frame,look});
 try{await page.waitForFunction(()=>window.cargoWalkDone,undefined,{timeout:35000});}catch(e){console.log('Walk failed',target,await page.evaluate(()=>({position:window.starAgent.state.position,local:window.starAgent.state.shipLocal,station:window.starAgent.state.station.local,mode:window.starAgent.state.mode,interaction:window.starAgent.state.interaction})));throw e;}finally{await page.evaluate(()=>{clearInterval(window.cargoWalkTimer);window.cargoPad.axes=[0,0,0,0];});}await frames(page);
}
async function fit(page){const result=await page.evaluate(()=>{const d=document.querySelector('#trading-dialog'),r=d.getBoundingClientRect(),c=d.querySelector('.gameplay-content')??d;return {width:[c.clientWidth,c.scrollWidth],height:[c.clientHeight,c.scrollHeight],clipped:[...d.querySelectorAll('button')].filter(e=>e.getClientRects().length).filter(e=>{const b=e.getBoundingClientRect();return b.top<r.top-2||b.bottom>r.bottom+2||b.left<r.left-2||b.right>r.right+2;}).map(b=>b.textContent)};});expect(result.clipped).toEqual([]);expect(result.height[1]).toBeLessThanOrEqual(result.height[0]+2);return result;}
async function aim(page,point){await page.evaluate(point=>{window.cargoAimDone=false;window.cargoAimTimer=setInterval(()=>{const n=window.starAgent.navigation,pad=window.cargoPad,target=n.fromShipLocal(n.position.clone().fromArray(point)).sub(n.position).applyQuaternion(n.orientation.clone().invert()),yaw=Math.atan2(target.x,-target.z),pitch=Math.atan2(target.y,Math.hypot(target.x,target.z));if(Math.abs(yaw)<.02&&Math.abs(pitch)<.02){pad.axes=[0,0,0,0];clearInterval(window.cargoAimTimer);window.cargoAimDone=true;return;}const a=x=>Math.abs(x)<.015?0:Math.sign(x)*Math.min(1,.19+Math.abs(x)*2);pad.axes[2]=a(yaw);pad.axes[3]=a(-pitch);},30);},point);await page.waitForFunction(()=>window.cargoAimDone,undefined,{timeout:12000});await frames(page);}
test('controller walks to trade terminal, buys eightSBU, returns through hatch and carries/stows real cargo',async({page,browser})=>{
 const {tap,button,choose,errors}=await setup(page);await tap(2);await page.waitForFunction(()=>window.starAgent.state.mode==='walk');await walk(page,[0,2.75,3]);await aim(page,[0,2.75,7]);await tap(2);await page.waitForFunction(()=>window.starAgent.state.doorProgress>.98);await walk(page,[0,1.75,8]);
 const floor=await page.evaluate(()=>window.starAgent.navigation.station.interiorBox.min.y);await walk(page,[-10,floor+1.75,18.8],'station');await walk(page,[-11,floor+1.75,20.5],'station');await aim(page,await page.evaluate(()=>{const n=window.starAgent.navigation;return n.toShipLocal(n.station.toWorld(n.position.clone().set(-12,n.station.interiorBox.min.y+1.5,22.69),n.position.clone())).toArray();}));await page.screenshot({path:`${evidence}/station-terminal.png`});await tap(2);await expect(page.locator('#trading-dialog')).toBeVisible();await fit(page);
 for(let i=0;i<8;i++)await choose('purchase-basalt');expect(await page.evaluate(()=>window.starAgent.state.trading.ships.find(s=>s.hull==='nomad').crates.length)).toBe(8);await page.screenshot({path:`${evidence}/nomad-trade.png`});
 await choose('purchase-basalt');await expect(page.locator('.trade-feedback')).toContainText('No cargo grid space');await choose('view-cargo');await page.screenshot({path:`${evidence}/manifest.png`});
 for(const size of [{width:390,height:844},{width:1440,height:900}]){await page.setViewportSize(size);await frames(page);await fit(page);await page.screenshot({path:`${evidence}/manifest-${size.width}.png`});}
 await button(7,true);await tap(1);await frames(page);expect(await page.evaluate(()=>window.starAgent.state.controller.armed)).toBe(false);await button(7,false);await page.waitForFunction(()=>window.starAgent.state.controller.armed);
 await walk(page,[-10,floor+1.75,18.8],'station');await walk(page,[0,1.75,8]);await walk(page,[0,2.75,2.75]);await aim(page,[1.24,1.7,2.76]);await page.screenshot({path:`${evidence}/nomad-full.png`});await tap(2);await choose('view-cargo');const id=await page.evaluate(()=>window.starAgent.state.trading.ships.find(s=>s.hull==='nomad').crates.find(c=>c.cell[1]===3).id);await choose('next-page');await choose('next-page');await choose(`take-${id}`);expect(await page.evaluate(()=>window.starAgent.state.trading.account.carried.sbu)).toBe(1);await tap(1);await frames(page);await page.screenshot({path:`${evidence}/hand-carry.png`});await tap(2);await choose('view-cargo');await choose('stow');expect(await page.evaluate(()=>window.starAgent.state.trading.account.carried)).toBe(null);await tap(1);
 expect(errors).toEqual([]);await writeFile(`${evidence}/controller.json`,JSON.stringify({browser:browser.version(),errors,state:await page.evaluate(()=>window.starAgent.state),physicalController:false},null,2));
});

test('Atlas full64SBU grid leaves real lift approach walkable; keyboard and phone inspect cargo',async({page,browser})=>{
 // Explicit capacity stress fixture; purchase-to-delivery is covered above.
 const {MiningStore}=await import('../../src/mining/store.js'),{emptyCommerce,ensureAccount}=await import('../../src/trading/model.js'),{placeCrate}=await import('../../src/cargo/grid.js');
 const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)},store=new MiningStore(storage),s=emptyCommerce();ensureAccount(s,'local-player');
 const ship=s.ships['local-player:atlas'];for(let i=0;i<8;i++)ship.crates.push(placeCrate('atlas',ship.crates,{id:`stress-${i}`,resource:'copper',sbu:64}));store.write({...store.state,commerce:s});
 await page.addInitScript(entries=>{window.__starAgentCargoTestSeed=entries;},[...values]);const {errors}=await setup(page,'atlas',true);
 await page.keyboard.press('f');await page.waitForFunction(()=>window.starAgent.state.mode==='walk');await walk(page,[0,5.75,-1]);await walk(page,[0,5.75,3]);await walk(page,[3.8,5.75,3]);await aim(page,[5.1,5.7,3]);await page.waitForFunction(()=>window.starAgent.state.trading.visuals.some(v=>v.objects>3));await page.screenshot({path:`${evidence}/atlas-full.png`});
 await page.keyboard.press('f');await expect(page.locator('#trading-dialog')).toBeVisible();await page.locator('[data-controller-key="view-cargo"]').click();await expect(page.locator('.trade-summary')).toContainText('512 / 512');await expect(page.locator('[data-controller-key="take-stress-0"]')).toBeDisabled();
 await page.setViewportSize({width:390,height:844});await fit(page);await page.locator('[data-controller-key="next-page"]').click();await fit(page);await page.screenshot({path:`${evidence}/atlas-phone.png`});await page.keyboard.press('Escape');
 expect(errors).toEqual([]);await writeFile(`${evidence}/atlas.json`,JSON.stringify({browser:browser.version(),errors,state:await page.evaluate(()=>window.starAgent.state),fixture:'eight64SBU crates preloaded for capacity inspection'},null,2));
});


test('controller builds a surface trading pad and walks to its terminal; phone shop fits',async({page,browser})=>{
 // Explicit Selene starting pose, then controller movement/UI only. Flight here is not asserted.
 const T=await import('three'),{SELENE,bodySurfacePoint}=await import('../../src/celestial.js'),{MOON_LANDING_DIRECTION}=await import('../../src/moon-world.js');
 const up=new T.Vector3(...MOON_LANDING_DIRECTION),position=bodySurfacePoint(up,SELENE,1.75),q=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),up).multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),12*Math.PI/8));
 const {tap,choose,errors}=await setup(page);
 await page.evaluate(({position,q})=>{const n=window.starAgent.navigation;n.position.fromArray(position);n.orientation.fromArray(q);n.shipPosition.copy(n.position).addScaledVector(n.normal,100);n.shipOrientation.fromArray(q);n.mode='walk';n.insideShip=false;n.dockedAtStation=false;n.spaceParked=false;n.cabinFlight=false;n.jumpHeight=0;n.jumpVelocity=0;n.velocity.set(0,0,0);},{position:position.toArray(),q:q.toArray()});
 await frames(page);await tap(9);await choose('tab-trade');await expect(page.locator('#trading-dialog')).toBeVisible();await choose('view-build');await fit(page);const credits=await page.evaluate(()=>window.starAgent.state.trading.account.credits);await choose('deploy-trade');
 await page.waitForFunction(()=>window.starAgent.state.trading.terminals.length===1);expect(await page.evaluate(()=>window.starAgent.state.trading.account.credits)).toBe(credits-500);await tap(1);await frames(page);
 await page.screenshot({path:`${evidence}/surface-pad.png`});
 const terminal=await page.evaluate(()=>window.starAgent.state.trading.terminals[0]);const target=new T.Vector3(0,2,17.5).applyQuaternion(new T.Quaternion(...terminal.quaternion)).add(new T.Vector3(...terminal.origin));await walk(page,target.toArray(),'world');await tap(2);await expect(page.locator('#trading-dialog')).toBeVisible();await choose('view-stock');await page.setViewportSize({width:390,height:844});await fit(page);await page.screenshot({path:`${evidence}/player-shop-phone.png`});await tap(1);
 expect(errors).toEqual([]);await writeFile(`${evidence}/surface-pad.json`,JSON.stringify({browser:browser.version(),errors,terminal,fixture:'Selene initial standing pose only; then controller build and walking',state:await page.evaluate(()=>window.starAgent.state)},null,2));
});
