import test from 'node:test';import assert from 'node:assert/strict';
import {Scene,Vector3,Quaternion,Group,MeshStandardMaterial} from 'three';
import {BuildSystem} from '../src/build/system.js';import {MiningStore} from '../src/mining/store.js';import {prepareSandbox,SANDBOX_BINS} from '../src/build/sandbox.js';import {SELENE} from '../src/celestial.js';
import {padApproaches,padLightPositions} from '../src/build/pad-kit.js';import {PIECES} from '../src/build/definitions.js';import {setLandingPadVisual} from '../src/build/visuals.js';import {constrainBuildStep} from '../src/build/collision.js';
const v=a=>new Vector3(...a);
function fixture(){const data=new Map(),disk={getItem:k=>data.get(k)??null,setItem:(k,x)=>data.set(k,x)},store=new MiningStore(disk);assert.ok(prepareSandbox(store).ok);const nav={mode:'walk',body:SELENE,altitude:1.75,position:new Vector3(),orientation:new Quaternion(),normal:new Vector3(0,1,0),keys:new Set(),gamepad:{suspend(){}},layout:{eyeHeight:1.75},stationDistance:10000},build=new BuildSystem({scene:new Scene(),nav,store,render:false,supplySources:()=>SANDBOX_BINS.map(b=>b.id)}),c=build.claims[0];nav.position.copy(build.toWorld(v([-6,1.75,6]),c));build.target=()=>build.toWorld(v([-15,.3,4]),c);return {store,build,disk,c};}
const concrete=store=>SANDBOX_BINS.reduce((sum,b)=>sum+store.container(b.id).items.concrete,0);
test('landing pad purchase atomically supplies four ramps, designation and matching cost',()=>{const f=fixture(),before=f.build.data.nextId,mass=concrete(f.store),count=f.c.pieces.length;f.build.begin('foundation-pad-small');assert.ok(f.build.preview.valid,f.build.preview.reason);const result=f.build.place();assert.ok(result.ok,result.message);const c=f.build.claims[0],pad=c.pieces.find(p=>p.id===result.pieceId);assert.equal(pad.landingPad,true);assert.equal(c.pieces.length,count+5);assert.equal(f.build.data.nextId,before+5);assert.equal(mass-concrete(f.store),232);assert.deepEqual(c.pieces.slice(-4),padApproaches(pad,before+1));assert.deepEqual(new MiningStore(f.disk).state.build,f.build.data);f.build.dispose();});
test('an occupied approach rejects the entire pad purchase without spending or placing',()=>{const f=fixture(),next=structuredClone(f.store.state);next.build.claims[0].pieces.push({id:`build-piece-${next.build.nextId++}`,type:'foundation',position:[-14,.3,4],rotation:0,doorOpen:false});assert.ok(f.store.write(next));const before=structuredClone(f.store.state);f.build.begin('foundation-pad-small');assert.match(f.build.preview.reason,/Approach ramp:.*occupied/);assert.equal(f.build.place().ok,false);assert.deepEqual(f.store.state,before);f.build.dispose();});
test('four approach ramps reach the full-size deck and support a rotated walking approach',()=>{for(const rotation of [0,Math.PI/3,Math.PI/2]){const pad={type:'foundation-pad-small',position:[0,.6,0],rotation};const ramps=padApproaches(pad);assert.equal(ramps.length,4);const ramp=ramps[0],toWorld=(x,y,z)=>[Math.cos(rotation)*x+Math.sin(rotation)*z,y,-Math.sin(rotation)*x+Math.cos(rotation)*z];let pos=toWorld(0,1.75,12.1);for(let i=0;i<50;i++){const z=12.1-(i+1)*.1,target=toWorld(0,pos[1]-.03,z);pos=constrainBuildStep(pos,target,[pad,...ramps],{eyeHeight:1.75}).point;}assert.ok(Math.abs(pos[1]-2.35)<.001,`${rotation}: no jump onto the deck`);assert.deepEqual(PIECES[pad.type].footprint,[16,16]);}});
test('landing beacons switch with power while painted markings remain visible',()=>{const root=new Group(),markings=new Group();markings.name='LandingPadMarkings';root.add(markings);const lens=new MeshStandardMaterial({name:'LandingLens',emissiveIntensity:1.2});root.userData.buildFinish={materials:new Map([['lens',lens]])};setLandingPadVisual(root,true,true);assert.equal(lens.emissiveIntensity,1.2);setLandingPadVisual(root,true,false);assert.equal(lens.emissiveIntensity,0);assert.equal(markings.visible,true);setLandingPadVisual(root,false,true);assert.equal(markings.visible,false);assert.equal(lens.emissiveIntensity,0);for(const [w,l]of [[16,16],[32,40],[48,72]])for(const [x,,z]of padLightPositions(w,l)){assert.ok(Math.abs(x)<w/2&&Math.abs(z)<l/2);assert.ok(Math.abs(x)>2.4||Math.abs(z)>2.4);}});
