import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import { SBU_SIZES,crateSize,capacitySBU,placeCrate,validGrid,canRemoveCrate,crateBounds } from '../src/cargo/grid.js';
import { emptyCommerce,ensureAccount,commerceCommand,validCommerce,shipKey } from '../src/trading/model.js';
import { SHIP_LAYOUT,constrainShipStep } from '../src/boarding.js';
import { FREIGHTER_LAYOUT,LIFTS } from '../src/freighter-layout.js';
import { constrainShipAttachments } from '../src/ship-attachment-collision.js';
const context={terminal:()=>true,docked:()=>true,crate:()=>true,grid:()=>true,loot:()=>true,haul:()=>true,resources:()=>1024};
function setup(){const s=emptyCommerce();ensureAccount(s,'alice',100000);ensureAccount(s,'bob',100000);return s;}
let id=0;function command(s,owner,m,ctx=context){return commerceCommand(s,owner,{commandId:`test-${++id}`,revision:s.revision,ship:shipKey(owner,'nomad'),terminal:'station:1',resource:'basalt',sbu:1,...m},ctx);}
test('SBU crate volume doubles with size; 64SBU is1.2×2.4×4.8m',()=>{for(const n of SBU_SIZES)assert.ok(Math.abs(crateSize(n).reduce((a,b)=>a*b,1)-n*.216)<1e-10);assert.deepEqual(crateSize(64),[1.2,2.4,4.8]);});
test('Nomad fits four1SBU crates; Atlas eight64SBU crates with no overlap or floating support',()=>{for(const [hull,n,size]of [['nomad',4,1],['atlas',8,64]]){const c=[];for(let i=0;i<n;i++){const p=placeCrate(hull,c,{id:`c-${i}`,sbu:size});assert.ok(p);c.push(p);}assert.equal(placeCrate(hull,c,{id:'overflow',sbu:1}),null);assert.equal(validGrid(hull,c),true);assert.equal(capacitySBU(hull),n*size);}});
test('full cargo keeps Nomad centreline and Atlas belly/side lifts physically clear',()=>{
 for(const hull of ['nomad','atlas']){const crates=[];while(true){const p=placeCrate(hull,crates,{sbu:hull==='nomad'?1:64});if(!p)break;crates.push(p);}const boxes=crates.map(c=>crateBounds(hull,c));
  for(let z=-1.2;z<3.8;z+=.1){const a=new THREE.Vector3(0,2.75,z),b=a.clone().add(new THREE.Vector3(0,0,.1));assert.deepEqual(constrainShipAttachments(a,b,boxes).toArray(),b.toArray());if(hull==='nomad')assert.deepEqual(constrainShipStep(a,b,true).toArray(),b.toArray());}
  if(hull==='atlas')for(const b of boxes){assert.ok(b.min[1]>=FREIGHTER_LAYOUT.floorY&&b.max[1]<9.3);for(const l of LIFTS)assert.ok(b.max[0]<=l.minX||b.min[0]>=l.maxX||b.max[2]<=l.minZ||b.min[2]>=l.maxZ);}
 }
});
test('buy validates physical fit and saves no partial oversized delivery',()=>{const s=setup();assert.throws(()=>command(s,'alice',{op:'buy',sbu:8}),/space/);assert.equal(s.accounts.alice.credits,100000);const r=command(s,'alice',{op:'buy',sbu:4});assert.equal(r.state.ships['alice:nomad'].crates.length,1);assert.equal(r.state.accounts.alice.credits,99920);assert.equal(validCommerce(r.state),true);});
test('take allows1SBU only and no unsupported stack; larger salvage conserves identity',()=>{let s=command(setup(),'alice',{op:'buy',sbu:2}).state;const c=s.ships['alice:nomad'].crates[0];assert.throws(()=>command(s,'bob',{op:'take',ship:'alice:nomad',crate:c.id}),/Only a 1/);s=command(s,'bob',{op:'haul',ship:'alice:nomad',destination:'bob:atlas',crate:c.id}).state;assert.equal(s.ships['alice:nomad'].crates.length,0);assert.equal(s.ships['bob:atlas'].crates[0].id,c.id);
 s=command(s,'alice',{op:'buy'}).state;const one=s.ships['alice:nomad'].crates[0];s=command(s,'bob',{op:'take',ship:'alice:nomad',crate:one.id}).state;assert.equal(s.accounts.bob.carried.id,one.id);s=command(s,'bob',{op:'stow'}).state;assert.equal(s.accounts.bob.carried,null);assert.equal(s.ships['bob:nomad'].crates[0].id,one.id);
});
test('stale, replayed, unreachable and unauthorised transactions cannot duplicate or steal',()=>{const s=setup(),m={commandId:'repeat',revision:0,op:'buy',ship:'alice:nomad',terminal:'station:1',resource:'copper',sbu:1};const r=commerceCommand(s,'alice',m,context);assert.equal(commerceCommand(r.state,'alice',m,context).state,r.state);assert.throws(()=>commerceCommand(r.state,'alice',{...m,commandId:'other'},context),/changed/);assert.throws(()=>command(r.state,'bob',{op:'take',ship:'alice:nomad',crate:r.state.ships['alice:nomad'].crates[0].id},{...context,loot:()=>false}),/Board/);assert.throws(()=>command(s,'alice',{op:'buy'},{...context,docked:()=>false}),/docked/);});
test('player stock settles both wallets exactly once and cannot be oversold',()=>{let s=setup();s.terminals['trade-1']={id:'trade-1',owner:'alice',position:[0,0,0],stock:{basalt:1},prices:{basalt:37}};s=command(s,'bob',{op:'buy',terminal:'trade-1'}).state;assert.equal(s.accounts.bob.credits,99963);assert.equal(s.accounts.alice.credits,100037);assert.equal(s.terminals['trade-1'].stock.basalt,0);assert.throws(()=>command(s,'bob',{op:'buy',terminal:'trade-1'}),/stock/);});
test('packing debits16kg perSBU and never imports insufficient loose ore',()=>{const s=setup();const r=command(s,'alice',{op:'pack',sbu:2});assert.equal(r.resourceDelta,-32);assert.throws(()=>command(s,'alice',{op:'pack',sbu:2},{...context,resources:()=>31}),/loose resources/);});

test('removing a supporting crate is denied without repacking its neighbours',()=>{const crates=[];for(let i=0;i<4;i++)crates.push(placeCrate('nomad',crates,{id:`support-${i}`,sbu:1}));assert.equal(canRemoveCrate('nomad',crates,crates[0].id),false);assert.equal(canRemoveCrate('nomad',crates,crates[2].id),true);});
