import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {buildStationColliders,constrainStationSweep} from '../station-collision.js';
import {PERIMETER as P} from './catalog.js';
const v=a=>new T.Vector3(...a);
const relative=(node,root)=>{const chain=[];for(let p=node;p&&p!==root;p=p.parent)chain.push(p);const m=new T.Matrix4();for(const p of chain.reverse()){p.updateMatrix();m.multiply(p.matrix);}return m;};
/** Unmodified articulated Bastion export, with a separate authored cylinder. */
export class PirateTower{
 constructor(scene,layout){this.layout=layout;this.scene=scene;this.group=new T.Group();this.group.name=`${layout.name} perimeter tower`;scene.add(this.group);this.origin=v(layout.tower).applyQuaternion(new T.Quaternion(...layout.claim.quaternion)).add(v(layout.claim.origin));this.quaternion=new T.Quaternion(...layout.claim.quaternion);this.parts=[];this.ready=false;this.error='';this.kick=[0,0];this.loader=new GLTFLoader();this.beams=[];this.disposed=false;
  this.readyPromise=Promise.all(['/models/pirate-tower.glb','/models/station-defense.glb'].map(url=>this.loader.loadAsync(url))).then(([tower,battery])=>{
   if(this.disposed)return;this.tower=tower.scene;this.battery=battery.scene;this.battery.position.y=P.towerHeight;this.battery.scale.setScalar(P.towerScale);this.group.add(this.tower,this.battery);
   this.yaw=this.battery.getObjectByName('Bastion_Yaw');this.pitch=this.battery.getObjectByName('Bastion_Pitch');this.muzzles=['Port','Starboard'].map(s=>this.battery.getObjectByName(`Bastion_Muzzle_${s}`));this.recoil=['Port','Starboard'].map(s=>this.battery.getObjectByName(`Bastion_Recoil_${s}`));
   if(!this.yaw||!this.pitch||this.muzzles.some(n=>!n)||this.recoil.some(n=>!n))throw Error('Hush Bastion articulation incomplete.');
   this.group.traverse(mesh=>{if(!mesh.isMesh)return;mesh.castShadow=mesh.receiveShadow=true;this.parts.push({mesh,tree:buildStationColliders(new T.Mesh(mesh.geometry)),matrix:new T.Matrix4(),inverse:new T.Matrix4()});});this.refresh();this.ready=true;
  }).catch(e=>{this.error=e.message;throw e;});
 }
 refresh(){for(const p of this.parts){p.matrix.copy(relative(p.mesh,this.group));p.inverse.copy(p.matrix).invert();}}
 aim(target,dt){if(!this.ready)return false;const p=target.clone().sub(this.origin).applyQuaternion(this.quaternion.clone().invert()).sub(new T.Vector3(0,P.towerHeight+9*P.towerScale,0));const yaw=Math.atan2(-p.x,-p.z),pitch=T.MathUtils.clamp(Math.atan2(p.y,Math.hypot(p.x,p.z)),-.2,Math.PI/2);const delta=T.MathUtils.euclideanModulo(yaw-this.yaw.rotation.y+Math.PI,Math.PI*2)-Math.PI;this.yaw.rotation.y+=T.MathUtils.clamp(delta,-dt*.7,dt*.7);this.pitch.rotation.x+=T.MathUtils.clamp(pitch-this.pitch.rotation.x,-dt*.6,dt*.6);this.refresh();return Math.abs(delta)<.012&&Math.abs(pitch-this.pitch.rotation.x)<.012;}
 muzzle(i){return new T.Vector3(0,0,this.kick[i]).applyMatrix4(relative(this.muzzles[i],this.group)).applyQuaternion(this.quaternion).add(this.origin);}
 direction(){return new T.Vector3(0,0,-1).applyQuaternion(this.pitch.quaternion).applyQuaternion(this.yaw.quaternion).applyQuaternion(this.quaternion);}
 shot(i,end){this.kick[i]=0;this.recoil[i].position.z=0;const start=this.muzzle(i);const geometry=new T.CylinderGeometry(.075,.075,1,6);geometry.rotateX(Math.PI/2);const material=new T.MeshBasicMaterial({color:0xffbd73,transparent:true,opacity:.9,depthWrite:false,toneMapped:false}),mesh=new T.Mesh(geometry,material);mesh.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),end.clone().sub(start).normalize());mesh.scale.z=start.distanceTo(end);this.scene.add(mesh);this.beams.push({mesh,position:start.clone().lerp(end,.5),age:0});this.kick[i]=.6;this.recoil[i].position.z=.6;this.refresh();return start;}
 raycast(start,direction,range,envelope){if(!this.ready)return null;const end=start.clone().addScaledVector(direction,range),inverse=this.quaternion.clone().invert(),a=start.clone().sub(this.origin).applyQuaternion(inverse),b=end.clone().sub(this.origin).applyQuaternion(inverse);const pad=envelope?Math.max(v(envelope.min).length(),v(envelope.max).length()):.004;if(new T.Line3(a,b).closestPointToPoint(new T.Vector3(0,9,0),true,new T.Vector3()).length()>50+pad)return null;
  let closest=null;for(const part of this.parts){const bounds=new T.Box3(),rotation=new T.Matrix3().setFromMatrix4(part.inverse);for(let i=0;i<8;i++){const extent=envelope?new T.Vector3(...[0,1,2].map(k=>(i&(1<<k)?envelope.max:envelope.min)[k])).applyQuaternion(envelope.orientation):new T.Vector3(i&1?.004:-.004,i&2?.004:-.004,i&4?.004:-.004);bounds.expandByPoint(extent.applyQuaternion(inverse).applyMatrix3(rotation));}const hit=constrainStationSweep(part.tree,[],a.clone().applyMatrix4(part.inverse),b.clone().applyMatrix4(part.inverse),bounds.min,bounds.max);if(hit.hit){const point=hit.point.applyMatrix4(part.matrix).applyQuaternion(this.quaternion).add(this.origin),distance=start.distanceTo(point);if(!closest||distance<closest.distance)closest={point,distance,normal:direction.clone().negate()};}}
  return closest;
 }
 update(dt,origin,{enabled=true,phase='idle'}={}){this.group.position.copy(this.origin).sub(origin);this.group.quaternion.copy(this.quaternion);this.group.visible=enabled&&this.origin.distanceToSquared(origin)<2400**2;if(this.ready){for(let i=0;i<2;i++){this.kick[i]=Math.max(0,this.kick[i]-dt*1.5);this.recoil[i].position.z=this.kick[i];}this.refresh();const status=this.tower.getObjectByName('Tower_AmberWarning');if(status)status.material.emissiveIntensity=phase==='disabled'?.08:phase==='charge'?2+Math.sin(performance.now()*.022):.6;}
  for(const b of [...this.beams]){b.age+=dt;b.mesh.position.copy(b.position).sub(origin);b.mesh.material.opacity=Math.max(0,.9*(1-b.age/.22));if(b.age>=.22){b.mesh.removeFromParent();b.mesh.geometry.dispose();b.mesh.material.dispose();this.beams.splice(this.beams.indexOf(b),1);}}
 }
 dispose(){this.disposed=true;this.group.removeFromParent();for(const b of this.beams){b.mesh.removeFromParent();b.mesh.geometry.dispose();b.mesh.material.dispose();}for(const root of [this.tower,this.battery])root?.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});}
}
