import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {MINING_KEY} from '../src/mining/store.js';
import {SANDBOX_PREFIX} from '../src/build/sandbox.js';
const out='/home/cees/.cache/star-agent-build-removal-evidence';
async function tap(page,i){await page.evaluate(i=>window.testPad.buttons[i]={pressed:true,value:1},i);await page.waitForFunction(i=>window.starAgent.navigation.gamepad.previous[i],i);await page.evaluate(i=>window.testPad.buttons[i]={pressed:false,value:0},i);await page.waitForFunction(i=>!window.starAgent.navigation.gamepad.previous[i],i);}
async function choose(page,key,navigates=false){const el=page.locator(`[data-controller-key="${key}"]`);for(let i=0;i<100;i++){if(await el.evaluate(e=>e===document.activeElement))break;await page.waitForFunction(()=>window.starAgent.navigation.gamepad.uiArmed);await tap(page,13);}await expect(el).toBeFocused();if(navigates)await page.evaluate(()=>window.testPad.buttons[0]={pressed:true,value:1});else await tap(page,0);}
const ready=page=>page.waitForFunction(()=>window.starAgent?.state.ready&&window.starAgent.state.controller.armed,null,{timeout:90000});
const saved=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),SANDBOX_PREFIX+MINING_KEY);
test.afterEach(async({page},info)=>{if(info.status===info.expectedStatus)return;await mkdir(out,{recursive:true});await page.screenshot({path:`${out}/failure.png`});await writeFile(`${out}/failure.json`,JSON.stringify(await page.evaluate(()=>window.starAgent?.state),null,2));});
async function aimAt(page,point){for(let i=0;i<140;i++){const error=await page.evaluate(point=>{const n=window.starAgent.navigation,local=n.position.clone().fromArray(point).sub(n.position).applyQuaternion(n.orientation.clone().invert());return [Math.atan2(local.x,-local.z),Math.atan2(local.y,Math.hypot(local.x,local.z))];},point);if(error.every(v=>Math.abs(v)<.03)){await page.evaluate(()=>window.testPad.axes.fill(0));return;}await page.evaluate(e=>window.testPad.axes=[0,0,...[e[0],-e[1]].map(v=>Math.sign(v)*Math.min(.7,.2+Math.abs(v)))],error);await page.waitForTimeout(90);}throw Error('Controller aim did not converge');}
const worldPoint=(page,p)=>page.evaluate(p=>{const c=window.starAgent.state.build.claims[0],n=window.starAgent.navigation;return n.position.clone().fromArray(p).applyQuaternion(n.orientation.clone().fromArray(c.quaternion)).add(n.position.clone().fromArray(c.origin)).toArray();},p);
async function selectBuild(page,id,tab){await tap(page,1);await page.waitForFunction(()=>window.starAgent.navigation.gamepad.uiArmed);for(let i=0;i<6&&!(await page.locator(`[data-controller-key="build-tab-${tab}"]`).getAttribute('aria-pressed')==='true');i++){await tap(page,5);await page.waitForFunction(()=>window.starAgent.navigation.gamepad.uiArmed);}await choose(page,`build-piece-${id}`);await ready(page);}
async function buildPiece(page,id,tab,point){await aimAt(page,await worldPoint(page,point));await selectBuild(page,id,tab);await page.waitForFunction(()=>window.starAgent.state.build.preview?.valid,null,{timeout:10000});const before=await page.evaluate(()=>window.starAgent.state.build.pieceCount);await tap(page,0);await page.waitForFunction(n=>window.starAgent.state.build.pieceCount===n+1,before);await tap(page,2);}

async function walkTo(page,point){await aimAt(page,point);await page.evaluate(()=>window.testPad.axes=[0,-.5,0,0]);await page.waitForFunction(point=>{const n=window.starAgent.navigation,c=window.starAgent.state.build.claims[0],delta=n.position.clone().fromArray(point).sub(n.position).applyQuaternion(n.orientation.clone().fromArray(c.quaternion).invert());return Math.hypot(delta.x,delta.z)<.45;},point,{timeout:45000});await page.evaluate(()=>window.testPad.axes.fill(0));}

test('controller removes one aimed piece, retains foundations under a held A and restores the edited base',async({page})=>{
 test.setTimeout(180000);await mkdir(out,{recursive:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.testPad={id:'Removal controller',index:0,connected:true,mapping:'standard',axes:[0,0,0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};navigator.getGamepads=()=>[window.testPad];});
 await page.goto('/?sandbox=build&intro=0&debug&seed=7291');await ready(page);await page.waitForFunction(()=>window.starAgent.state.build.assetsReady);const baseline=await saved(page);
 await buildPiece(page,'crate','pieces',[0,.3,2]);const built=await saved(page),crate=built.build.claims[0].pieces.find(p=>p.type==='crate');expect(crate).toBeTruthy();
 await aimAt(page,await worldPoint(page,[crate.position[0],crate.position[1]+.6,crate.position[2]]));await tap(page,1);await page.waitForFunction(()=>window.starAgent.navigation.gamepad.uiArmed);await choose(page,'build-remove-tool');await ready(page);
 await expect(page.locator('.build-selected')).toHaveText('REMOVE TOOL');await page.waitForFunction(()=>window.starAgent.state.build.preview?.valid);await expect(page.locator('.build-placement')).toContainText('Storage crate');await page.screenshot({path:`${out}/remove-target.png`});
 await page.evaluate(()=>window.testPad.buttons[0]={pressed:true,value:1});await page.waitForFunction(n=>window.starAgent.state.build.pieceCount===n,baseline.build.claims[0].pieces.length);await page.waitForTimeout(400);expect((await saved(page)).build.claims[0].pieces).toEqual(baseline.build.claims[0].pieces);
 await page.evaluate(()=>window.testPad.buttons[0]={pressed:false,value:0});await ready(page);expect((await saved(page)).remote[`build-crate-${crate.id.split('-').at(-1)}`]).toBeUndefined();
 await tap(page,2);await ready(page);await page.reload();await ready(page);expect((await saved(page)).build.claims[0].pieces).toEqual(baseline.build.claims[0].pieces);expect(errors).toEqual([]);
 await page.screenshot({path:`${out}/removed-and-reloaded.png`});await writeFile(`${out}/journey.json`,JSON.stringify({input:'Injected Gamepad only, shipped sandbox and actual placement',removed:crate.id,pieces:(await saved(page)).build.claims[0].pieces.length,errors},null,2));
});
