import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';

const out='test-results/fleet-opening-captures';
const state=page=>page.evaluate(()=>window.starAgent.state);
const distance=(a,b)=>Math.hypot(...a.map((v,i)=>v-b[i]));

test('solo and authenticated multiplayer retain the shoulder opening and physical handover',async({page,browser})=>{
  await mkdir(out,{recursive:true});const errors=[],stages={};
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.goto('/?debug');
  await page.waitForFunction(()=>window.starAgent?.state.ready,null,{timeout:120000});
  await expect(page.locator('#multiplayer-account-dialog')).toBeVisible();
  await page.locator('[data-mp-continue]').click();
  await page.waitForFunction(()=>window.starAgent.state.opening.phase==='cinematic');
  stages.soloStart=await state(page);
  expect(stages.soloStart.opening.authoritative).toBe(false);
  expect(stages.soloStart.character.visible).toBe(true);
  expect(distance(stages.soloStart.camera.position,stages.soloStart.position)).toBeGreaterThan(3);
  await page.waitForTimeout(1200);stages.soloDolly=await state(page);
  expect(distance(stages.soloStart.position,stages.soloDolly.position)).toBeLessThan(.02);
  expect(distance(stages.soloStart.camera.position,stages.soloDolly.camera.position)).toBeGreaterThan(.04);
  expect(stages.soloDolly.opening.doors).toBeGreaterThan(stages.soloStart.opening.doors);
  await page.screenshot({path:out+'/solo-shoulder.png'});
  await page.keyboard.press('KeyW');
  await page.waitForFunction(()=>window.starAgent.state.opening.phase==='playing');
  await page.locator('#multiplayer-access').click();
  await page.locator('[data-auth-view=register]').click();
  const stamp=String(Date.now()).slice(-8),callsign='Fleet'+stamp;
  await page.locator('#mp-register-email').fill('fleet-opening-'+stamp+'@example.test');
  await page.locator('#mp-register-callsign').fill(callsign);
  await page.locator('#mp-register-password').fill('Disposable-opening-7291!');
  await page.locator('[data-auth-form=register] button[type=submit]').click();
  await expect(page.locator('[data-account-callsign]')).toHaveText(callsign);
  await page.locator('[data-join]').click();
  await page.waitForFunction(()=>window.starAgent.state.multiplayer.connected&&window.starAgent.state.opening.authoritative);
  await page.locator('#multiplayer-account-dialog [data-mp-close]').click();
  stages.onlineStart=await state(page);
  expect(stages.onlineStart.opening.phase).toBe('cinematic');
  expect(stages.onlineStart.mode).toBe('walk');
  expect(stages.onlineStart.station.docked).toBe(true);
  expect(stages.onlineStart.character.visible).toBe(true);
  expect(distance(stages.onlineStart.camera.position,stages.onlineStart.position)).toBeGreaterThan(3);
  await page.waitForTimeout(1200);stages.onlineDolly=await state(page);
  expect(distance(stages.onlineStart.position,stages.onlineDolly.position)).toBeLessThan(.02);
  expect(distance(stages.onlineStart.camera.position,stages.onlineDolly.camera.position)).toBeGreaterThan(.04);
  expect(stages.onlineDolly.opening.authoritative).toBe(true);
  await page.screenshot({path:out+'/multiplayer-shoulder.png'});
  await page.keyboard.down('KeyW');
  await page.waitForFunction(()=>window.starAgent.state.opening.phase==='playing');
  await page.waitForTimeout(250);await page.keyboard.up('KeyW');
  stages.onlineControl=await state(page);
  expect(distance(stages.onlineDolly.position,stages.onlineControl.position)).toBeGreaterThan(.08);
  expect(stages.onlineControl.multiplayer.connected).toBe(true);
  await writeFile(out+'/receipt.json',JSON.stringify({browser:browser.version(),stages,errors,
    isolation:'Disposable in-memory API8106, no account/pose/door mocks or shared database access'},null,2));
  expect(errors).toEqual([]);
});
