import { test, expect } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';

const evidence='/tmp/star-agent-moon-evidence';
async function chooseDestination(page,name,modifiers=[]){
  await page.keyboard.press('KeyH');
  await expect(page.locator('#help-dialog')).toBeVisible();
  const menu=page.locator('#quick-transit-menu');
  const summary=page.locator('#quick-transit-menu > summary');
  await expect(summary).toHaveText('Quick transit');
  await expect.poll(()=>menu.evaluate(element=>element.open)).toBe(false);
  await summary.click();
  await expect.poll(()=>menu.evaluate(element=>element.open)).toBe(true);
  await menu.locator(`[data-destination="${name}"]`).click({modifiers});
  await expect(page.locator('#help-dialog')).toBeHidden();
  await expect.poll(()=>menu.evaluate(element=>element.open)).toBe(false);
}
test('Selene landing, ramp exploration, lunar jump, reboarding and launch render correctly',async({page,browser})=>{
  test.setTimeout(300000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.goto('/?intro=0&debug');await page.waitForFunction(()=>window.starAgent?.state.ready);
  await page.evaluate(()=>window.starAgent.setRenderScale(.55));
  await mkdir(evidence,{recursive:true});
  await page.keyboard.press('Tab');await page.screenshot({path:`${evidence}/orbit.png`});await page.keyboard.press('Tab');
  const before=await page.evaluate(()=>window.starAgent.state.position);
  await chooseDestination(page,'moon',['Shift']);
  await expect(page.locator('#course-guidance')).toContainText('Selene');
  expect(await page.evaluate(()=>window.starAgent.state.position)).toEqual(before);
  await chooseDestination(page,'moon');
  await page.waitForFunction(()=>!window.starAgent.state.transiting&&Number(getComputedStyle(document.getElementById('transit')).opacity)===0);
  await expect(page.locator('#mode-label')).toHaveText('LUNAR FLIGHT');
  await expect(page.locator('#altitude-reference')).toHaveText('ABOVE SELENE');
  expect(await page.evaluate(()=>window.starAgent.state.altitude)).toBeCloseTo(180,5);
  await page.keyboard.press('l');
  await page.waitForFunction(()=>window.starAgent.state.mode==='landed',null,{timeout:90000});
  await page.waitForFunction(()=>window.starAgent.state.moon.lod>=14);
  const landed=await page.evaluate(()=>window.starAgent.state);
  expect(landed.body).toBe('selene');expect(landed.biome).toBe('SELENE · AIRLESS MOON');expect(landed.atmosphereFraction).toBe(0);
  await page.keyboard.press('f');
  await page.keyboard.down('w');await page.waitForFunction(()=>window.starAgent.state.shipLocal[2]>2.3);await page.keyboard.up('w');await page.keyboard.press('x');
  await page.keyboard.press('f');await page.waitForFunction(()=>window.starAgent.state.doorProgress===1);
  await page.keyboard.down('w');await page.waitForFunction(()=>window.starAgent.state.shipLocal[2]>12);await page.keyboard.up('w');await page.keyboard.press('x');
  const outside=await page.evaluate(()=>window.starAgent.state);
  expect(outside.insideShip).toBe(false);expect(outside.altitude).toBeCloseTo(1.75,5);
  await expect(page.locator('#mode-label')).toHaveText('LUNAR EXPLORATION');
  await page.keyboard.press('Tab');await page.screenshot({path:`${evidence}/surface.png`});
  await page.keyboard.down('Space');await page.waitForFunction(()=>window.starAgent.navigation.jumpHeight>.1);await page.keyboard.up('Space');
  await page.waitForFunction(()=>window.starAgent.navigation.jumpHeight>2);
  await page.waitForFunction(()=>window.starAgent.navigation.jumpHeight===0,null,{timeout:60000});
  const orientation=await page.evaluate(()=>window.starAgent.navigation.orientation.toArray());
  await page.evaluate(()=>{const nav=window.starAgent.navigation;nav.orientToward(nav.position.clone().set(0,0,0),nav.normal);});
  await page.waitForTimeout(400);await page.screenshot({path:`${evidence}/aeon-from-surface.png`});
  await page.evaluate(()=>{const nav=window.starAgent.navigation;nav.orientToward(nav.shipPosition.clone().addScaledVector(nav.normal,2),nav.normal);});
  await page.waitForTimeout(400);await page.screenshot({path:`${evidence}/ship-on-selene.png`});
  await page.evaluate(value=>window.starAgent.navigation.orientation.fromArray(value),orientation);
  await page.keyboard.down('s');await page.waitForFunction(()=>window.starAgent.state.shipLocal[2]<-1.4);await page.keyboard.up('s');await page.keyboard.press('x');
  await page.keyboard.press('f');await page.waitForFunction(()=>window.starAgent.state.mode==='landed');
  await page.keyboard.press('l');expect(await page.evaluate(()=>window.starAgent.state.mode)).toBe('flight');
  expect(await page.evaluate(()=>window.starAgent.state.altitude)).toBeGreaterThan(10);
  await page.keyboard.press('o');await page.waitForFunction(()=>!window.starAgent.state.transiting);
  expect(await page.evaluate(()=>window.starAgent.state.body)).toBe('aeon');
  const gpu=await page.evaluate(()=>{const gl=document.querySelector('canvas').getContext('webgl2'),ext=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),viewport:[innerWidth,innerHeight]};});
  await writeFile(`${evidence}/environment.json`,JSON.stringify({browser:browser.version(),...gpu,landed,outside,errors},null,2));
  expect(errors).toEqual([]);
});
