import {test,expect} from '@playwright/test';
import {writeFile,readFile} from 'node:fs/promises';
import {out,frames,setup,walk,aim,capture,graphics,pirateControllerJourney} from './pirate-fixtures.js';
test.afterEach(async({page},info)=>{if(info.status!==info.expectedStatus){try{await capture(page,'failure-'+info.retry);}catch{}}});

test.describe('phone',()=>{
test.use({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
test('keyboard and native phone use the service panel and actual trade handlers',async({page,browser})=>{
 const {errors,warnings}=await setup(page);
 expect(await page.evaluate(()=>matchMedia('(pointer:coarse)').matches&&navigator.maxTouchPoints>0)).toBe(true);
 // Presentation regression uses explicit nearby poses, separate from the full controller route.
 async function pose(x,z){await page.evaluate(({x,z})=>{const n=window.starAgent.navigation,s=window.starAgent.state.pirateCompound.site,q=n.orientation.clone().fromArray(s.quaternion),o=n.position.clone().fromArray(s.origin);n.mode='walk';n.insideShip=false;n.cabinFlight=false;n.enabled=true;n.position.set(x,s.deck+n.layout.eyeHeight,z).applyQuaternion(q).add(o);n.orientation.copy(q);n.velocity.set(0,0,0);n.shipPosition=n.position.clone().fromArray(s.pad);n.shipOrientation.copy(q);n.shipVelocity.set(0,0,0);},{x,z});await frames(page);}
 await pose(-16,-5.5);await page.keyboard.press('f');await expect(page.locator('#pirate-service')).toBeVisible();await capture(page,'service-keyboard');await page.keyboard.press('Escape');await expect(page.locator('#pirate-service')).not.toBeVisible();
 await frames(page);await page.locator('.pirate-service-action:visible').tap();await expect(page.locator('#pirate-service')).toBeVisible();await page.locator('#pirate-service [data-isolate]').tap();expect(await page.evaluate(()=>window.starAgent.state.pirateCompound.unlocked)).toBe(true);expect(await page.locator('#pirate-service').evaluate(d=>d.scrollWidth<=d.clientWidth+2)).toBe(true);await capture(page,'service-phone');await page.locator('#pirate-service [data-close]').tap();
 await pose(6,-19.8);await expect(page.locator('[data-cabin-interact]')).toHaveText('Open trade');await page.locator('[data-cabin-interact]').tap();await expect(page.locator('#trading-dialog')).toBeVisible();const before=await page.evaluate(()=>window.starAgent.state.trading.markets['pirate-hush'].stock.ice);await page.locator('[data-controller-key="purchase-ice"]').tap();await expect(page.locator('.trade-feedback')).toContainText('Loaded 1 SBU');expect(await page.evaluate(()=>window.starAgent.state.trading.markets['pirate-hush'].stock.ice)).toBe(before-1);await page.locator('#trading-dialog [data-controller-key="view-cargo"]').tap();await capture(page,'trade-phone');expect(await page.locator('#trading-dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+2)).toBe(true);await page.locator('#trading-dialog .gameplay-resume').tap();await page.waitForFunction(()=>window.starAgent.state.enabled);
 expect(errors).toEqual([]);await writeFile(`${out}/native-phone.json`,JSON.stringify({browser:browser.version(),graphics:await graphics(page),errors,warnings,controlledPose:true,physicalController:false},null,2));
});
});

test('controller physically approaches, isolates tower, trades and returns to play',({page,browser})=>pirateControllerJourney({page,browser}));

test('work yard diagnostic keeps the corrected fixture HDR finite',async({page,browser})=>{
 const {errors,warnings}=await setup(page);
 await page.evaluate(()=>{const n=window.starAgent.navigation,s=window.starAgent.state.pirateCompound.site,q=n.orientation.clone().fromArray(s.quaternion),o=n.position.clone().fromArray(s.origin),world=a=>n.position.clone().fromArray([a[0],s.deck+a[1],a[2]]).applyQuaternion(q).add(o);n.mode='walk';n.enabled=false;n.insideShip=false;n.position.copy(world([-2,3,24]));n.orientToward(world([-8,1,8]),n.normal);n.velocity.set(0,0,0);});
 await page.waitForFunction(()=>window.starAgent.state.moon.pending===0&&window.starAgent.state.moon.effects.settled,undefined,{timeout:60000});await frames(page);await page.addStyleTag({content:'body > :not(canvas) { visibility: hidden !important; }'});
 // Capture the existing scene HDR target through a fixture-only draw callback.
 await page.evaluate(()=>{window.starAgent.navigation.station.scene.getObjectByName('Crimson salvage fixtures').children[2].traverse(mesh=>{if(!mesh.isMesh)return;const previous=mesh.onBeforeRender;mesh.onBeforeRender=function(renderer,...args){window.pirateHDR={renderer,target:renderer.getRenderTarget()};previous.call(this,renderer,...args);};});});await frames(page);
 const hdr=()=>page.evaluate(()=>{const {renderer,target}=window.pirateHDR,x=Math.floor(850/innerWidth*target.width),y=Math.floor((1-710/innerHeight)*target.height),w=Math.floor(210/innerWidth*target.width),h=Math.floor(300/innerHeight*target.height),pixels=new Uint16Array(w*h*4);renderer.readRenderTargetPixels(target,x,y,w,h,pixels);let nonFinite=0,nonZero=0;for(let i=0;i<pixels.length;i++){if(i%4===3)continue;if((pixels[i]&0x7c00)===0x7c00)nonFinite++;if(pixels[i])nonZero++;}return {type:target.texture.type,width:target.width,height:target.height,roi:[x,y,w,h],nonFinite,nonZero};});
 await capture(page,'crimson-work-yard');const corrected=await hdr();
 // Restore only the exact six invalid source normals to isolate the cause.
 const repairs=JSON.parse(await readFile(new URL('../assets/pirate-props/manifest.json',import.meta.url),'utf8')).assets.find(a=>a.id==='floodlight').normalRepairs;
 await page.evaluate(repairs=>{window.pirateNormalUndo=[];window.starAgent.navigation.station.scene.getObjectByName('Crimson salvage fixtures').children[2].traverse(mesh=>{if(!mesh.isMesh)return;const normal=mesh.geometry.attributes.normal;for(const r of repairs){normal.setXYZ(r.vertex,...r.source);window.pirateNormalUndo.push(()=>normal.setXYZ(r.vertex,...r.value));}normal.needsUpdate=true;window.pirateNormalUndo.push(()=>normal.needsUpdate=true);});},repairs);await frames(page);await capture(page,'invalid-source-normals');const previous=await hdr();
 await page.evaluate(()=>window.pirateNormalUndo.forEach(undo=>undo()));await frames(page);await capture(page,'restored-normals');
 await writeFile(`${out}/lamp-hdr.json`,JSON.stringify({browser:browser.version(),graphics:await graphics(page),corrected,previous,repairs,errors,warnings,fixture:true},null,2));expect(corrected.type).toBe(1016);expect(corrected.nonZero).toBeGreaterThan(0);expect(corrected.nonFinite).toBe(0);expect(previous.nonFinite).toBeGreaterThan(0);expect(errors).toEqual([]);
 for(const [name,eye,look] of [['compound-overview',[48,28,61],[0,5,-10]],['crimson-workbench',[-5,2,10],[-8,1,6]]]){await page.evaluate(({eye,look})=>{const n=window.starAgent.navigation,s=window.starAgent.state.pirateCompound.site,q=n.orientation.clone().fromArray(s.quaternion),o=n.position.clone().fromArray(s.origin),world=a=>n.position.clone().fromArray([a[0],s.deck+a[1],a[2]]).applyQuaternion(q).add(o);n.position.copy(world(eye));n.orientToward(world(look),n.normal);},{eye,look});await frames(page);await capture(page,name);}
});


test('tower telegraphs weaker fire, stops on retreat, and renders in compound',async({page,browser})=>{
 const {errors,warnings}=await setup(page);
 // Art/balance fixture only; this does not establish controller navigation.
 await page.evaluate(()=>{const n=window.starAgent.navigation,s=window.starAgent.state.pirateCompound.site,q=n.orientation.clone().fromArray(s.quaternion),o=n.position.clone().fromArray(s.origin);n.position.set(0,s.deck+40,100).applyQuaternion(q).add(o);n.velocity.set(0,0,0);n.orientToward(n.position.clone().fromArray(s.tower),n.normal);});
 await page.waitForFunction(()=>window.starAgent.state.pirateCompound.phase==='charge',undefined,{timeout:25000});await capture(page,'charging-tower');const before=await page.evaluate(()=>window.starAgent.state.combat.player);await page.waitForFunction(()=>window.starAgent.state.pirateCompound.shots>=3,undefined,{timeout:15000});const after=await page.evaluate(()=>window.starAgent.state.combat.player);expect(after.hull).toBe(before.hull);expect(after.shield).toBeGreaterThan(0);expect(after.shield).toBeLessThan(before.shield);await capture(page,'survived-burst');
 await page.evaluate(()=>{const n=window.starAgent.navigation,s=window.starAgent.state.pirateCompound.site;n.position.set(0,s.deck+40,350).applyQuaternion(n.orientation.clone().fromArray(s.quaternion)).add(n.position.clone().fromArray(s.origin));n.velocity.set(0,0,0);});const shots=await page.evaluate(()=>window.starAgent.state.pirateCompound.shots);await page.waitForTimeout(2500);expect(await page.evaluate(()=>window.starAgent.state.pirateCompound.shots)).toBe(shots);
 await page.evaluate(()=>{const n=window.starAgent.navigation,s=window.starAgent.state.pirateCompound.site,q=n.orientation.clone().fromArray(s.quaternion),o=n.position.clone().fromArray(s.origin);n.mode='walk';n.enabled=false;n.insideShip=false;n.position.set(48,s.deck+28,61).applyQuaternion(q).add(o);n.orientToward(n.position.clone().set(0,s.deck+5,-10).applyQuaternion(q).add(o),n.normal);n.velocity.set(0,0,0);});await page.waitForFunction(()=>window.starAgent.state.moon.pending===0&&window.starAgent.state.moon.effects.settled,undefined,{timeout:60000});await frames(page);await page.addStyleTag({content:'body > :not(canvas) { visibility: hidden !important; }'});await capture(page,'compound-overview');
 const performance=await page.evaluate(async()=>{const samples=[],start=performance.now();let previous=start;while(performance.now()-start<5000){await new Promise(r=>requestAnimationFrame(r));const now=performance.now(),s=window.starAgent.state;samples.push({ms:now-previous,draws:s.drawCalls,triangles:s.triangles,scale:s.renderScale});previous=now;}const times=samples.map(s=>s.ms).sort((a,b)=>a-b);return {durationMs:performance.now()-start,samples:samples.length,medianMs:times[Math.floor(times.length*.5)],p95Ms:times[Math.floor(times.length*.95)],first:samples[0],last:samples.at(-1),countsIncludeShadowPasses:true};});
 for(const [name,eye,look] of [['crimson-work-yard',[-2,3,24],[-8,1,8]],['cylindrical-tower',[-2,10,7],[-16,7,-12]],['crimson-generator',[-7,2,-21],[-10,1,-27]],['locked-exchange',[6,1.75,-18],[6,1.3,-22]]]){
  await page.evaluate(({eye,look})=>{const n=window.starAgent.navigation,s=window.starAgent.state.pirateCompound.site,q=n.orientation.clone().fromArray(s.quaternion),o=n.position.clone().fromArray(s.origin),world=a=>n.position.clone().fromArray([a[0],s.deck+a[1],a[2]]).applyQuaternion(q).add(o);n.position.copy(world(eye));n.orientToward(world(look),n.normal);},{eye,look});await frames(page);await capture(page,name);
 }
 expect(errors).toEqual([]);await writeFile(`${out}/visual-balance.json`,JSON.stringify({browser:browser.version(),graphics:await graphics(page),errors,warnings,before,after,retreatShots:shots,performance,fixture:true,state:await page.evaluate(()=>window.starAgent.state.pirateCompound)},null,2));
});
