import {test,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
import {setup,walk,aim,capture,graphics,focusInterruption,frames} from './recovery-helpers.js';
import {brake,climb,steerTarget,levelForPad,flyToPad,exitAndTerminal,reboard} from './recovery-flight.js';
const state=p=>p.evaluate(()=>window.starAgent.state),out=process.env.TRANSPORT_EVIDENCE;
async function chord(page,tap,key){await page.evaluate(()=>{for(const i of [4,5])window.transportPad.buttons[i]={pressed:true,value:1};});await frames(page);await tap(key);await page.evaluate(()=>{for(const i of [4,5])window.transportPad.buttons[i]={pressed:false,value:0};});await frames(page);}
async function travel(page,tap,id){
 await steerTarget(page,id);const before=(await state(page)).position;
 await page.evaluate(id=>{window.recoveryFlight={id,samples:[]};window.recoveryFlightTimer=setInterval(()=>{const s=window.starAgent.state;window.recoveryFlight.samples.push({time:performance.now(),position:s.position,phase:s.travel?.phase??null});},20);},id);
 try{await chord(page,tap,12);await page.waitForFunction(before=>{const s=window.starAgent.state;return !s.travel&&window.recoveryFlight.samples.some(p=>p.phase)&&Math.hypot(...s.position.map((v,i)=>v-before[i]))>1000;},before,{timeout:180000});}
 finally{await page.evaluate(()=>{clearInterval(window.recoveryFlightTimer);(window.recoveryFlights??=[]).push(window.recoveryFlight);});}
 const samples=await page.evaluate(()=>window.recoveryFlight.samples);expect(samples.some(p=>p.phase)).toBe(true);expect(new Set(samples.map(p=>p.position.join(','))).size).toBeGreaterThan(2);console.log('Recovery drive recorded:',id,samples.length,'samples');
}
async function world(page,point,frame='wreck'){return page.evaluate(({point,frame})=>{const n=window.starAgent.navigation,m=window.starAgent.state.trading.account.recovery.active;return frame==='ship'?n.fromShipLocal(n.position.clone().fromArray(point)).toArray():n.position.clone().fromArray(point).applyQuaternion(n.orientation.clone().fromArray(m.quaternion)).add(n.position.clone().fromArray(m.position)).toArray();},{point,frame});}
async function orient(page,q){
 await page.evaluate(q=>{window.recoveryOrientDone=false;window.recoveryOrient=setInterval(()=>{const n=window.starAgent.navigation,p=window.transportPad,inv=n.orientation.clone().invert(),desired=n.orientation.clone().fromArray(q),forward=n.position.clone().set(0,0,-1).applyQuaternion(desired).applyQuaternion(inv),up=n.position.clone().set(0,1,0).applyQuaternion(desired).applyQuaternion(inv),yaw=Math.atan2(forward.x,-forward.z),pitch=Math.atan2(forward.y,Math.hypot(forward.x,forward.z)),roll=Math.atan2(up.x,up.y),a=x=>Math.abs(x)<.009?0:Math.sign(x)*Math.min(1,.19+Math.abs(x)*2);p.axes=[0,0,a(yaw),a(-pitch)];p.buttons[4]={pressed:roll<-.025,value:+(roll<-.025)};p.buttons[5]={pressed:roll>.025,value:+(roll>.025)};p.buttons[6]={pressed:true,value:1};if(Math.abs(yaw)<.02&&Math.abs(pitch)<.02&&Math.abs(roll)<.035){clearInterval(window.recoveryOrient);window.recoveryOrientDone=true;}},30);},q);
 try{await page.waitForFunction(()=>window.recoveryOrientDone,undefined,{timeout:60000});}finally{await page.evaluate(()=>{clearInterval(window.recoveryOrient);window.transportPad.axes.fill(0);for(const i of [4,5,6])window.transportPad.buttons[i]={pressed:false,value:0};});}
}
// Full 3D flight/EVA feedback. The only writes are standard Gamepad controls.
async function move(page,goal,{speed=330,tolerance=.3,held=false}={}){
 await page.evaluate(({goal,speed,tolerance,held})=>{window.recoveryMoveDone=false;window.recoveryMove=setInterval(()=>{const n=window.starAgent.navigation,p=window.transportPad,delta=n.position.clone().fromArray(goal).sub(n.position),distance=delta.length(),eva=n.mode==='eva',desired=delta.normalize().multiplyScalar(Math.min(speed,Math.sqrt(Math.max(0,distance-tolerance/2)*(eva?1.5:8)))),error=desired.sub(n.velocity).applyQuaternion(n.orientation.clone().invert()),gain=eva?1.5:20,magnitude=Math.hypot(error.x,error.z)/gain,scale=magnitude>.02?(.16+.84*Math.min(1,magnitude))/(magnitude*gain):0;p.axes[0]=error.x*scale;p.axes[1]=error.z*scale;p.buttons[0]={pressed:error.y>(eva?.15:.5),value:+(error.y>(eva?.15:.5))};p.buttons[1]={pressed:error.y<-(eva?.15:.5),value:+(error.y<-(eva?.15:.5))};p.buttons[6]={pressed:false,value:0};if((distance<tolerance&&n.speed<(eva?.45:1.5))||(n.mode==='walk'&&distance<.75)){p.axes[0]=p.axes[1]=0;p.buttons[0]=p.buttons[1]={pressed:false,value:0};p.buttons[6]={pressed:true,value:1};window.recoveryMoveDone=true;clearInterval(window.recoveryMove);}},30);},{goal,speed,tolerance,held});
 try{await page.waitForFunction(()=>window.recoveryMoveDone,undefined,{timeout:180000});await page.evaluate(()=>window.transportPad.buttons[6]={pressed:true,value:1});await page.waitForFunction(()=>window.starAgent.state.speed<.01,undefined,{timeout:12000});}finally{await page.evaluate(()=>{clearInterval(window.recoveryMove);window.transportPad.axes[0]=window.transportPad.axes[1]=0;for(const i of [0,1,6])window.transportPad.buttons[i]={pressed:false,value:0};});}await frames(page);
}
async function lock(page,button,id){
 for(let attempt=0;attempt<3;attempt++){
  await button(7,true);
  await page.waitForFunction(id=>window.starAgent.state.trading.tractor.held===id||window.starAgent.state.trading.tractor.message.includes('lock expired'),id,{timeout:18000});
  if((await state(page)).trading.tractor.held===id)return;
  await capture(page,`expired-lock-${id}-${attempt}`);await button(7,false);await page.waitForFunction(()=>window.starAgent.state.controller.armed);
  await aim(page,(await state(page)).trading.loose.find(c=>c.id===id).position,'world');
 }
 throw Error('Three explicit release/re-engage attempts could not retain the tractor lease');
}
async function guide(page,tap,point,frame='wreck'){
 const goal=await world(page,point,frame);await aim(page,goal,'world');const distance=await page.evaluate(goal=>window.starAgent.navigation.position.distanceTo(window.starAgent.navigation.position.clone().fromArray(goal)),goal);
 for(let i=0;i<26;i++){const held=(await state(page)).trading.tractor.distance;if(Math.abs(held-distance)<.24)break;await tap(held>distance?12:13);}
 await page.waitForFunction(goal=>{const s=window.starAgent.state,n=window.starAgent.navigation,c=s.trading.loose.find(c=>c.id===s.trading.tractor.held);return c&&n.position.clone().fromArray(c.position).distanceTo(n.position.clone().fromArray(goal))<.48;},goal,{timeout:18000});
}
async function approach(page,tap,button,guarded=false){
 await tap(9);await page.waitForFunction(()=>Boolean(document.querySelector('dialog[open]')));
 // Ship panel remains the shared discoverable control for cruise and weapon.
 const choose=async key=>{for(let i=0;i<95;i++){if(await page.evaluate(k=>document.activeElement?.dataset.controllerKey===k,key)){await tap(0);return;}await tap(13);}throw Error('Missing '+key);};
 await choose('tab-ship');if((await state(page)).combatMode)await choose('combat-mode');if(guarded){if(!await page.locator('dialog[open]').count()){await tap(9);await choose('tab-ship');}await choose('weapon-laser');}if(await page.locator('dialog[open]').count())await tap(1);if((await state(page)).landingGear.target)await chord(page,tap,13);await page.waitForFunction(()=>window.starAgent.state.landingGear.progress<.02);if((await state(page)).altitude<20500)await climb(page,button,20500);await capture(page,'departure');
 await tap(9);await choose('tab-contracts');await choose('recovery-contracts');await choose('recovery-track');if(await page.locator('dialog[open]').count())await tap(1);const m=(await state(page)).trading.account.recovery.active;await travel(page,tap,`wreck-${m.id}`);await capture(page,guarded?'guarded-drive-arrival':'drive-arrival');
 const q=await page.evaluate(()=>{const n=window.starAgent.navigation,m=window.starAgent.state.trading.account.recovery.active;return n.orientation.clone().fromArray(m.quaternion).multiply(n.orientation.clone().setFromAxisAngle(n.position.clone().set(0,1,0),Math.PI)).toArray();});
 await orient(page,q);await move(page,await world(page,[0,60,guarded?1000:150]),{tolerance:2});await brake(page,button);
 if(!guarded){const goal=await page.evaluate(({q,root})=>{const n=window.starAgent.navigation;return n.position.clone().fromArray(root).add(n.position.clone().fromArray(n.layout.seatEye).applyQuaternion(n.orientation.clone().fromArray(q))).toArray();},{q,root:await world(page,[0,1.6,46])});await move(page,goal,{speed:15,tolerance:.6});await brake(page,button);}
 await page.waitForFunction(()=>window.starAgent.state.recovery.asset==='ready'&&window.starAgent.state.trading.account.recovery.active.phase==='recover');await capture(page,guarded?'guarded-wreck':'disabled-atlas');
}
test.afterEach(async({page},info)=>{if(info.status!==info.expectedStatus){try{await capture(page,'failure');console.log('Recovery failure',JSON.stringify(await page.evaluate(()=>{const s=window.starAgent.state;return {mode:s.mode,position:s.position,shipLocal:s.shipLocal,speed:s.speed,interaction:s.interaction,recovery:s.recovery,mission:s.trading.account.recovery,tractor:s.trading.tractor,combat:s.combat.phase,focus:document.activeElement?.dataset.controllerKey,controller:s.controller};})));}catch{}}});

test('controller flies to disabled Atlas, EVAs, tractors original crates, returns and deposits',async({page,browser})=>{
 const {tap,button,choose,errors,warnings}=await setup(page);await tap(9);await choose('tab-contracts');await choose('recovery-contracts');await capture(page,'contracts');await choose('recovery-accept-silent-atlas');const accepted=(await state(page)).trading.account.recovery.active;expect((await state(page)).trading.loose).toHaveLength(0);await expect(page.locator('[data-controller-key="recovery-deposit"]')).toBeDisabled();await tap(1);
 await approach(page,tap,button);expect((await state(page)).trading.loose).toHaveLength(2);expect((await state(page)).recovery.models).toBe(1);
 await tap(2);await page.waitForFunction(()=>window.starAgent.state.mode==='walk');await walk(page,[0,2.75,3],'ship');await aim(page,[0,2.75,7]);await tap(2);await page.waitForFunction(()=>window.starAgent.state.doorProgress>.98);await walk(page,[0,1.75,8],'ship');await page.waitForFunction(()=>window.starAgent.state.mode==='eva');await capture(page,'physical-eva-exit');await move(page,await world(page,[45,25,55]),{speed:8,tolerance:.4});await brake(page,button);await aim(page,await world(page,[0,6,0]),'world');await capture(page,'disabled-atlas-exterior');
 await tap(9);await choose('tab-contracts');await choose('recovery-contracts');await choose('recovery-tractor');await page.waitForFunction(()=>window.starAgent.state.trading.tractor.active&&window.starAgent.state.controller.armed);
 for(let index=0;index<2;index++){
  await move(page,await world(page,[0,4.4,31]),{speed:2,tolerance:.25});await brake(page,button);const crate=(await state(page)).trading.loose.find(c=>c.recovery?.id===accepted.id);await aim(page,crate.position,'world');await lock(page,button,crate.id);await capture(page,`tractor-at-wreck-${index}`);
  if(index===0){
   await tap(9);await page.waitForFunction(()=>!window.starAgent.state.trading.tractor.held);await button(7,false);await page.waitForFunction(()=>window.starAgent.navigation.gamepad.uiArmed);await button(7,true);await tap(1);expect((await state(page)).controller.armed).toBe(false);await button(7,false);await page.waitForFunction(()=>window.starAgent.state.controller.armed);
   await aim(page,(await state(page)).trading.loose.find(c=>c.id===crate.id).position,'world');await lock(page,button,crate.id);await focusInterruption(page,button);await page.waitForFunction(()=>!window.starAgent.state.trading.tractor.held);
   for(const mode of ['disconnect','replacement','unsupported']){
    await aim(page,(await state(page)).trading.loose.find(c=>c.id===crate.id).position,'world');await lock(page,button,crate.id);await page.evaluate(mode=>{if(mode==='disconnect')window.transportDisconnected=true;if(mode==='replacement')window.transportPad.id+=' replacement';if(mode==='unsupported')window.transportPad.mapping='';},mode);await page.waitForFunction(()=>!window.starAgent.state.trading.tractor.held);const stopped=(await state(page)).trading.loose.find(c=>c.id===crate.id).position;await page.evaluate(()=>{window.transportDisconnected=false;window.transportPad.mapping='standard';});await frames(page);expect((await state(page)).controller.armed).toBe(false);expect((await state(page)).trading.loose.find(c=>c.id===crate.id).position).toEqual(stopped);await button(7,false);await page.waitForFunction(()=>window.starAgent.state.controller.armed);
   }
   await aim(page,(await state(page)).trading.loose.find(c=>c.id===crate.id).position,'world');await lock(page,button,crate.id);await capture(page,'sealed-tractor-interruption-recovery');
  }
  await guide(page,tap,[0,4.4,25]);await tap(14);await guide(page,tap,[0,4.4,27]);
  // Back out at suit speed below the tractor's cargo speed, leaving room for
  // the entire box through the real opening and across the zero-G gap.
  await move(page,await world(page,[0,4.4,35]),{speed:1.2,tolerance:.25,held:true});await guide(page,tap,[0,4.4,31]);await capture(page,`crate-through-atlas-ramp-${index}`);
  await move(page,await world(page,[0,4.4,36]),{speed:1,tolerance:.25,held:true});await guide(page,tap,[0,1.6,7],'ship');await guide(page,tap,[0,1.6+index*.6,3],'ship');await page.waitForFunction(()=>Boolean(window.starAgent.state.trading.tractor.slot));await capture(page,`crate-at-own-grid-${index}`);await tap(2);await page.waitForFunction(index=>window.starAgent.state.trading.ships.find(s=>s.hull==='nomad').crates.length===index+1,index);await button(7,false);await page.waitForFunction(()=>window.starAgent.state.controller.armed);
 }
 await tap(15);await capture(page,'both-original-crates-secured');await aim(page,[0,2.75,0]);
 // Slow physical EVA attachment at the player's own open ramp.
 await move(page,await world(page,[0,1.95,7],'ship'),{speed:.8,tolerance:.35});await page.waitForFunction(()=>window.starAgent.state.mode==='walk');await walk(page,[0,2.75,3],'ship');await walk(page,[0,2.75,-1.65],'ship');await aim(page,[0,2.75,-3]);await tap(2);await page.waitForFunction(()=>window.starAgent.state.mode==='flight');
 await tap(9);await choose('tab-contracts');await choose('recovery-contracts');await choose('recovery-delivery');if(await page.locator('dialog[open]').count())await tap(1);await travel(page,tap,'settlement-aeon');await levelForPad(page,'settlement-aeon');await flyToPad(page,'settlement-aeon');await brake(page,button);await tap(3);await page.waitForFunction(()=>window.starAgent.state.mode==='landed',undefined,{timeout:120000});await exitAndTerminal(page,tap);await choose('view-recovery');await capture(page,'delivery-terminal');const before=(await state(page)).trading.account.credits;await choose('recovery-deposit');await page.waitForFunction(()=>window.starAgent.state.trading.account.recovery.completed===1);const complete=(await state(page)).trading;expect(complete.account.credits).toBe(before+900);expect(complete.ships.find(s=>s.hull==='nomad').crates).toHaveLength(0);
 await page.setViewportSize({width:390,height:844});await capture(page,'phone-completion');expect(await page.locator('#trading-dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+2)).toBe(true);await page.setViewportSize({width:1440,height:900});await button(7,true);await tap(1);expect((await state(page)).controller.armed).toBe(false);await button(7,false);await page.waitForFunction(()=>window.starAgent.state.controller.armed);await focusInterruption(page,button);
 for(const mode of ['disconnect','replacement','unsupported']){await button(7,true);await page.evaluate(mode=>{if(mode==='disconnect')window.transportDisconnected=true;if(mode==='replacement')window.transportPad.id+=' replacement';if(mode==='unsupported')window.transportPad.mapping='';},mode);await frames(page);expect((await state(page)).controller.armed).toBe(false);await page.evaluate(()=>{window.transportDisconnected=false;window.transportPad.mapping='standard';});await frames(page);expect((await state(page)).controller.armed).toBe(false);await button(7,false);await page.waitForFunction(()=>window.starAgent.state.controller.armed);}
 await walk(page,[-2,0,-12]);await walk(page,[9,0,-12]);await walk(page,[9,0,30]);await reboard(page,tap);await tap(3);await page.waitForFunction(()=>window.starAgent.state.mode==='flight');await capture(page,'return-to-play');expect(errors).toEqual([]);await writeFile(`${out}/controller-receipt.json`,JSON.stringify({browser:browser.version(),graphics:await graphics(page),errors,warnings,physicalController:false,route:'Supported Aeon orbit start; every later gameplay action is standard Gamepad, navigation is read only for feedback.',accepted,complete:complete.account.recovery,flights:await page.evaluate(()=>window.recoveryFlights)},null,2));
});

test('guarded recovery uses actual defending ships and saves clearance',async({page,browser})=>{
 const {tap,button,choose,errors,warnings}=await setup(page);await tap(9);await choose('tab-contracts');await choose('recovery-contracts');await choose('recovery-accept-raider-claim');await tap(1);await approach(page,tap,button,true);expect((await state(page)).trading.account.recovery.active.cleared).toBe(false);expect((await state(page)).trading.loose).toHaveLength(2);
 await tap(9);await choose('tab-ship');if(!(await state(page)).combatMode)await choose('combat-mode');if(await page.locator('dialog[open]').count())await tap(1);await page.waitForFunction(()=>window.starAgent.state.effects.weaponStatus==='WEAPONS READY');
 await page.evaluate(()=>{window.recoveryFight=setInterval(()=>{const s=window.starAgent.state,n=window.starAgent.navigation,p=window.transportPad;if(s.trading.account.recovery.active.cleared||!['transit','engage'].includes(s.combat.phase)){p.axes.fill(0);p.buttons[7]={pressed:false,value:0};return;}const enemy=s.combat.enemies.find(e=>e.id===s.combat.targetId&&e.hull>0),destination=s.combat.phase==='transit'?s.combat.point:enemy?.position;if(!destination)return;const local=n.position.clone().fromArray(destination).sub(n.position).applyQuaternion(n.orientation.clone().invert()),yaw=Math.atan2(local.x,-local.z),pitch=Math.atan2(local.y,Math.hypot(local.x,local.z)),a=x=>Math.abs(x)<.003?0:Math.sign(x)*Math.min(1,.18+Math.abs(x)*2.5);p.axes=[Math.sin(performance.now()/1800)*.55,local.length()>1000?-.4:.2,a(yaw),a(-pitch)];p.buttons[6]={pressed:s.speed>100,value:+(s.speed>100)};const fire=Math.abs(yaw)<.045&&Math.abs(pitch)<.045;p.buttons[7]={pressed:fire,value:+fire};},35);});
 try{await page.waitForFunction(()=>window.starAgent.state.combat.hits>0,undefined,{timeout:90000});await capture(page,'defending-flight');await page.waitForFunction(()=>window.starAgent.state.trading.account.recovery.active.cleared||['failed','aborted'].includes(window.starAgent.state.combat.phase),undefined,{timeout:240000});}finally{await page.evaluate(()=>{clearInterval(window.recoveryFight);window.transportPad.axes.fill(0);for(const i of [6,7])window.transportPad.buttons[i]={pressed:false,value:0};});}
 const s=await state(page);expect(s.trading.account.recovery.active.cleared).toBe(true);expect(s.combat.reports[0].kills).toBe(2);await capture(page,'defenders-cleared');await tap(9);await choose('tab-contracts');await choose('recovery-contracts');await capture(page,'guarded-recovery-authorized');await choose('recovery-abandon');await tap(1);expect((await state(page)).trading.loose).toHaveLength(0);expect(errors).toEqual([]);await writeFile(`${out}/guarded-receipt.json`,JSON.stringify({browser:browser.version(),graphics:await graphics(page),errors,warnings,physicalController:false,report:s.combat.reports[0],mission:s.trading.account.recovery.active},null,2));
});

test('keyboard entry and native phone recovery actions retain private single acceptance',async({page,browser})=>{
 const {errors,warnings}=await setup(page);
 async function keyboardChoose(key){for(let i=0;i<100;i++){if(await page.evaluate(k=>document.activeElement?.dataset.controllerKey===k,key)){await page.keyboard.press('Enter');await frames(page);return;}await page.keyboard.press('Tab');}throw Error('Missing keyboard action '+key);}
 await page.keyboard.press('Escape');await keyboardChoose('tab-contracts');await keyboardChoose('recovery-contracts');await keyboardChoose('recovery-accept-silent-atlas');expect((await state(page)).trading.loose).toHaveLength(0);
 await page.evaluate(()=>window.transportDisconnected=true);await frames(page);await page.setViewportSize({width:390,height:844});const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});
 async function touch(key){
  for(let i=0;i<6;i++){
   const box=await page.locator(`[data-controller-key="${key}"]`).boundingBox(),panel=await page.locator('.trade-content').boundingBox();
   if(box.y>=panel.y+2&&box.y+box.height<=panel.y+panel.height-2)break;
   const x=panel.x+panel.width*.75,lo=panel.y+panel.height-12,hi=panel.y+12,start=box.y<panel.y?hi:lo,end=box.y<panel.y?lo:hi;
   await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y:start,id:1}]});for(let n=1;n<=8;n++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:start+(end-start)*n/8,id:1}]});await frames(page);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await frames(page);
  }
  const b=await page.locator(`[data-controller-key="${key}"]`).boundingBox();expect(b.y).toBeGreaterThan(0);expect(b.y+b.height).toBeLessThan(844);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2,id:1}]});await frames(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await frames(page);
 }
 await capture(page,'phone-active-contract');const credits=(await state(page)).trading.account.credits;await touch('recovery-abandon');await touch('recovery-accept-broken-convoy');await capture(page,'phone-hard-contract');await expect(page.locator('[data-controller-key="recovery-deposit"]')).toBeDisabled();expect((await state(page)).trading.account.recovery.active.job).toBe('broken-convoy');expect((await state(page)).trading.loose).toHaveLength(0);await touch('recovery-abandon');expect((await state(page)).trading.account.credits).toBe(credits);await page.keyboard.press('Escape');await page.waitForFunction(()=>window.starAgent.state.enabled&&!document.querySelector('dialog[open]'));expect(errors).toEqual([]);await writeFile(`${out}/keyboard-touch-receipt.json`,JSON.stringify({browser:browser.version(),graphics:await graphics(page),errors,warnings,nativeTouch:true,keyboardContractEntry:true,scope:'Contract actions only; full flight and hauling use the separate controller journey.',physicalController:false},null,2));await cdp.detach();
});
