import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {MINING_KEY} from '../src/mining/store.js';
const evidence='/tmp/star-agent-ship-radius';
const axes=(page,a)=>page.evaluate(a=>window.testPad.axes=a,a);
const tap=async(page,i)=>{await page.evaluate(i=>window.testPad.buttons[i]={pressed:true,value:1},i);await page.waitForFunction(i=>window.starAgent.navigation.gamepad.previous[i],i,{timeout:10000});await page.evaluate(i=>window.testPad.buttons[i]={pressed:false,value:0},i);await page.waitForFunction(i=>!window.starAgent.navigation.gamepad.previous[i],i,{timeout:10000});};
async function choose(page,key){const el=page.locator(`[data-controller-key="${key}"]`);for(let i=0;i<100;i++){if(await el.evaluate(e=>e===document.activeElement))break;await page.waitForFunction(()=>window.starAgent.navigation.gamepad.uiArmed);await tap(page,13);}await expect(el).toBeFocused();await tap(page,0);}
const cargo=page=>page.evaluate(()=>Object.fromEntries(window.starAgent.state.containers.containers.map(c=>[c.id,c.items])));
const saved=page=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),MINING_KEY);
const distance=page=>page.evaluate(()=>{const n=window.starAgent.navigation;return n.position.distanceTo(n.shipPosition);});
async function travelDistance(page,axis,predicate){await axes(page,[0,axis,0,0]);await page.waitForFunction(({threshold,greater})=>{const n=window.starAgent.navigation,d=n.position.distanceTo(n.shipPosition);return greater?d>threshold:d<threshold;},predicate,{timeout:60000});await axes(page,[0,0,0,0]);}
test.afterEach(async({page},info)=>{if(info.status===info.expectedStatus)return;await mkdir(evidence,{recursive:true});await writeFile(`${evidence}/failure.json`,JSON.stringify(await page.evaluate(()=>({storage:Object.fromEntries(Object.entries(localStorage)),state:window.starAgent?.state})).catch(e=>({error:e.message})),null,2));});
test('normal starter ship kit supports controller building and cargo within50m only',async({page,browser})=>{
 test.setTimeout(360000);page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await mkdir(evidence,{recursive:true});
 // Fresh browser storage: only the standard controller is injected. Resources
 // come exclusively from the game's normal one-time starter-kit allocation.
 await page.addInitScript(()=>{window.testPad={id:'Injected standard starter-radius controller',index:0,connected:true,mapping:'standard',axes:[0,0,0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};navigator.getGamepads=()=>[window.testPad];});
 await page.goto('/?intro=0&debug');await page.waitForFunction(()=>window.starAgent?.state.ready&&window.starAgent.state.controller.armed&&window.starAgent.state.mining.ready,null,{timeout:90000});
 const initial=await cargo(page),initialSave=await saved(page);expect(initialSave.starterConstruction).toEqual({version:1,claimed:true});for(const[id,q]of Object.entries({concrete:80,'metal-stock':16,conductor:3,glass:4}))expect(initial.ship[id]).toBe(q);for(const id of ['concrete','metal-stock','conductor','glass'])expect(initial.pack[id]).toBe(0);
 console.log('normal starter kit verified');
 await tap(page,9);await choose(page,'destination-moon');await page.waitForFunction(()=>window.starAgent.state.body==='selene'&&!window.starAgent.state.transiting&&window.starAgent.state.controller.armed);await tap(page,3);await page.waitForFunction(()=>window.starAgent.state.mode==='landed');await tap(page,2);await page.waitForFunction(()=>window.starAgent.state.mode==='walk');
 await axes(page,[0,-1,0,0]);await page.waitForFunction(()=>window.starAgent.state.shipLocal[2]>2.3);await axes(page,[0,0,0,0]);await tap(page,2);await page.waitForFunction(()=>window.starAgent.state.doorProgress===1);await axes(page,[0,-1,0,0]);await page.waitForFunction(()=>window.starAgent.state.shipLocal[2]>26);await axes(page,[0,0,0,0]);expect(await page.evaluate(()=>window.starAgent.state.insideShip)).toBe(false);expect(await distance(page)).toBeLessThan(50);
 console.log('physically outside ship within radius',await distance(page));
 await tap(page,9);await choose(page,'build');await choose(page,'build-piece-mainframe');await page.waitForFunction(()=>window.starAgent.state.controller.armed);await page.waitForFunction(()=>window.starAgent.state.build.preview?.valid);expect(await page.evaluate(()=>window.starAgent.state.build.preview.sources)).toContain('ship');await page.screenshot({path:`${evidence}/starter-core-preview.png`});await tap(page,7);await page.waitForFunction(()=>window.starAgent.state.build.pieceCount===1);await tap(page,1);
 const afterCore=await cargo(page);expect(afterCore.ship['metal-stock']).toBe(11);expect(afterCore.ship.conductor).toBe(0);expect(afterCore.ship.glass).toBe(2);expect(afterCore.pack).toEqual(initial.pack);console.log('mainframe paid directly from normal ship kit');
 await tap(page,8);await choose(page,'location-ship');const key=await page.locator('[data-from="ship"][data-item="concrete"]').first().getAttribute('data-controller-key');await choose(page,key);await choose(page,'transfer-one');expect((await cargo(page)).pack.concrete).toBe(1);await choose(page,'deposit-all');expect((await cargo(page)).pack.concrete).toBe(0);expect((await cargo(page)).ship.concrete).toBe(80);
 await page.screenshot({path:`${evidence}/near-ship-cargo-desktop.png`});await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${evidence}/near-ship-cargo-phone.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.setViewportSize({width:1440,height:900});await tap(page,1);
 // Sidestep the placed core before walking forward across the cargo boundary.
 const start=await page.evaluate(()=>window.starAgent.state.position);await axes(page,[1,0,0,0]);await page.waitForFunction(start=>window.starAgent.navigation.position.distanceTo(window.starAgent.navigation.position.clone().fromArray(start))>=12,start);await axes(page,[0,0,0,0]);await travelDistance(page,-1,{threshold:52,greater:true});const outside=await distance(page);console.log('walked outside cargo radius',outside);
 await tap(page,8);await expect(page.locator('[data-controller-key="location-ship"]')).toHaveCount(0);await expect(page.locator('[data-controller-key="deposit-all"]')).not.toBeVisible();await page.screenshot({path:`${evidence}/outside-cargo-radius.png`});await tap(page,1);
 const beforeRejected=await cargo(page);await tap(page,9);await choose(page,'build');await choose(page,'build-piece-foundation');await page.waitForFunction(()=>window.starAgent.state.controller.armed);const preview=await page.evaluate(()=>window.starAgent.state.build.preview);expect(preview.sources).not.toContain('ship');expect(preview.valid).toBe(false);expect(preview.cost.concrete).toBe(12);await tap(page,7);expect(await page.evaluate(()=>window.starAgent.state.build.pieceCount)).toBe(1);expect(await cargo(page)).toEqual(beforeRejected);await page.screenshot({path:`${evidence}/outside-build-source.png`});await tap(page,1);
 await travelDistance(page,1,{threshold:45,greater:false});await tap(page,8);await choose(page,'location-ship');await expect(page.locator('[data-container="ship"]')).toBeVisible();await tap(page,1);const finalCargo=await cargo(page),finalSave=await saved(page);expect(finalSave.progression).toEqual(initialSave.progression);await page.reload();await page.waitForFunction(()=>window.starAgent?.state.ready,null,{timeout:90000});expect(await cargo(page)).toEqual(finalCargo);expect((await saved(page)).starterConstruction).toEqual({version:1,claimed:true});expect(await page.evaluate(()=>window.starAgent.state.build.pieceCount)).toBe(1);expect(errors).toEqual([]);
 await writeFile(`${evidence}/journey.json`,JSON.stringify({browser:browser.version(),fixture:'No inventory or pose fixture; normal one-time starter kit',input:'Injected standard Gamepad; physical controller untested',outsideDistance:outside,outsidePreview:preview,initial:initialSave.starterConstruction,finalCargo,errors},null,2));
});
