import { test, expect } from '@playwright/test';

test('Blender ship: physical cargo access, persistent transfers, live MFDs and boarding', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => {errors.push(error.message);console.log('PAGE ERROR',error.message);});
  page.on('console', message => { if (message.type() === 'error' && /THREE|WebGL|shader/i.test(message.text())) errors.push(message.text()); });
  await page.goto('/?debug=1');
  await page.waitForFunction(() => window.starAgent?.state.ready && window.starAgent.state.shipAsset === 'ready', null, { timeout: 60000 });
  await page.evaluate(() => window.starAgent.setRenderScale(.4));
  await page.evaluate(() => window.starAgent.transit('forest'));
  await page.keyboard.press('KeyL');
  await page.waitForFunction(() => window.starAgent.state.mode === 'landed', null, { timeout: 90000 });
  await page.waitForFunction(() => window.starAgent.state.mfds.every(screen => screen.values.length === 3));
  expect(await page.evaluate(() => window.starAgent.state.mfds.map(screen => screen.title))).toEqual(['FLIGHT', 'NAVIGATION', 'SYSTEMS', 'CARGO']);
  await page.keyboard.press('Tab');
  await page.evaluate(() => window.starAgent.setRenderScale(1));
  await page.waitForTimeout(800);
  await page.screenshot({ path: '/tmp/nomad-game-cockpit.png' });
  await page.evaluate(() => window.starAgent.setRenderScale(.4));
  await page.keyboard.press('Tab');
  await page.keyboard.press('KeyF');
  await page.keyboard.down('KeyW');
  await page.waitForFunction(() => window.starAgent.state.shipLocal[2] > .9);
  await page.keyboard.up('KeyW');await page.keyboard.press('KeyX');
  expect(await page.evaluate(() => window.starAgent.state.interaction)).toContain('CARGO');
  const before = await page.evaluate(() => window.starAgent.state.inventory);
  await page.keyboard.press('KeyF');
  await expect(page.getByRole('dialog', { name: 'Ship inventory' })).toBeVisible();
  await page.waitForFunction(() => window.starAgent.state.storageProgress === 1);
  await page.getByRole('button', { name: 'Take Repair kit', exact: true }).click();
  const after = await page.evaluate(() => window.starAgent.state.inventory);
  expect(after.ship.repair).toBe(before.ship.repair - 1);
  expect(after.pack.repair).toBe(before.pack.repair + 1);
  expect(after.shipMass + after.packMass).toBe(before.shipMass + before.packMass);
  await page.waitForFunction(() => window.starAgent.state.mfds[3].values[0].includes(`${window.starAgent.state.inventory.shipMass.toFixed(1)} /`));
  // Movement, help and quick-transit shortcuts must not escape the modal.
  const local = await page.evaluate(() => window.starAgent.state.shipLocal);
  await page.keyboard.press('KeyO');await page.keyboard.press('KeyH');
  await page.keyboard.down('KeyW');await page.waitForTimeout(300);await page.keyboard.up('KeyW');
  expect(await page.evaluate(() => window.starAgent.state.shipLocal)).toEqual(local);
  await expect(page.locator('#help-dialog')).not.toBeVisible();
  await page.screenshot({ path: '/tmp/nomad-game-inventory.png' });
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog', { name: 'Ship inventory' })).not.toBeVisible();
  await page.waitForFunction(() => window.starAgent.state.storageProgress === 0);
  await page.keyboard.down('KeyW');
  await page.waitForFunction(() => window.starAgent.state.shipLocal[2] > 2.3);
  await page.keyboard.up('KeyW');await page.keyboard.press('KeyX');await page.keyboard.press('KeyF');
  await page.waitForFunction(() => window.starAgent.state.doorProgress === 1);
  await page.keyboard.down('KeyW');await page.waitForFunction(() => window.starAgent.state.shipLocal[2] > 10);
  await page.keyboard.up('KeyW');await page.keyboard.press('KeyX');
  expect(await page.evaluate(() => window.starAgent.state.insideShip)).toBe(false);
  await page.evaluate(() => window.starAgent.navigation.look(Math.PI, 0));
  await page.keyboard.press('Tab');
  await page.evaluate(() => window.starAgent.setRenderScale(1));await page.waitForTimeout(800);
  await page.screenshot({ path: '/tmp/nomad-game-exterior.png' });
  await page.evaluate(() => window.starAgent.setRenderScale(.4));await page.keyboard.press('Tab');
  await page.keyboard.down('KeyW');await page.waitForFunction(() => window.starAgent.state.shipLocal[2] < 2.4);
  await page.keyboard.up('KeyW');await page.keyboard.press('KeyX');await page.keyboard.press('KeyF');
  expect(await page.evaluate(() => window.starAgent.state.doorOpen)).toBe(false);
  await page.keyboard.down('KeyW');await page.waitForFunction(() => window.starAgent.state.shipLocal[2] < -1.4);
  await page.keyboard.up('KeyW');await page.keyboard.press('KeyX');await page.keyboard.press('KeyF');
  expect(await page.evaluate(() => window.starAgent.state.mode)).toBe('landed');
  await page.keyboard.press('KeyL');
  expect(await page.evaluate(() => window.starAgent.state.mode)).toBe('flight');
  await page.reload();await page.waitForFunction(() => window.starAgent?.state.ready, null, { timeout: 60000 });
  expect(await page.evaluate(() => window.starAgent.state.inventory)).toEqual(after);
  expect(errors).toEqual([]);
});

test('missing GLB keeps the ship boardable and cargo usable', async ({ page }) => {
  const errors = [];page.on('pageerror', error => {errors.push(error.message);console.log('PAGE ERROR',error.message);});
  await page.route('**/models/nomad.glb', route => route.abort());
  await page.goto('/?debug=1');
  await page.waitForFunction(() => window.starAgent?.state.ready && window.starAgent.state.shipAsset === 'fallback', null, { timeout: 60000 });
  await page.evaluate(() => {
    const app = window.starAgent, nav = app.navigation;
    nav.transit(app.destinations.forest, 3.2);nav.touchDown();nav.embark();
  });
  await page.keyboard.down('KeyW');await page.waitForFunction(() => window.starAgent.state.shipLocal[2] > .9);
  await page.keyboard.up('KeyW');await page.keyboard.press('KeyX');await page.keyboard.press('KeyF');
  await expect(page.getByRole('dialog', { name: 'Ship inventory' })).toBeVisible();
  await page.getByRole('button', { name: 'Take Survey scanner', exact: true }).click();
  expect(await page.evaluate(() => window.starAgent.state.inventory.pack.scanner)).toBe(1);
  await page.keyboard.press('Escape');
  expect(await page.evaluate(() => window.starAgent.state.mode)).toBe('walk');
  expect(errors).toEqual([]);
});
