"""Original Meridian Bastion station battery; metres, game +Y up / -Z bore.

Rebuild (CPU authoring/export; no renderer):
  env ALSOFT_DRIVERS=null blender -b --factory-startup -noaudio \
    --python-exit-code 1 --python blender/build_station_defense.py

Run this checked-in file from any cwd. Optional -- --root /path/to/checkout.
The shared assets/station-defense/layout.json is READ ONLY. Textures, editable
Blender source, GLB and measured manifest are generated by this one builder.
"""
from pathlib import Path
import argparse
import hashlib
import json
import math
import random
import struct
import subprocess
import sys
import tempfile
import zlib

import bpy
import bmesh
from mathutils import Matrix, Vector
from mathutils.bvhtree import BVHTree

parser = argparse.ArgumentParser()
parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
args = parser.parse_args(sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else [])
ROOT = args.root.resolve()
SOURCE = ROOT / 'assets/station-defense'
TEXTURES = SOURCE / 'textures'
OUT = ROOT / 'public/models/station-defense.glb'
LAYOUT_PATH = SOURCE / 'layout.json'
LAYOUT_BYTES = LAYOUT_PATH.read_bytes()
LAYOUT = json.loads(LAYOUT_BYTES)
assert LAYOUT['yawNode'] == 'Bastion_Yaw'
assert LAYOUT['pitchNode'] == 'Bastion_Pitch'
assert LAYOUT['pitchPivot'] == [0, 9, 0]
assert LAYOUT['muzzles'] == [
    {'node': 'Bastion_Muzzle_Port', 'position': [-4.2, 0, -29]},
    {'node': 'Bastion_Muzzle_Starboard', 'position': [4.2, 0, -29]}]
assert LAYOUT['baseBounds'] == {'min': [-10, 0, -10], 'max': [10, 4, 10]}
for p in (TEXTURES, OUT.parent):
    p.mkdir(parents=True, exist_ok=True)

# Original deterministic swatches. This new atlas retains the Meridian palette,
# but does not copy an image, generated map or previous gun geometry. Relief is
# authored independently of colour; there are no diagonal/periodic scuff stripes.
EDGE = 512
PALETTE = [(215, 222, 212), (31, 42, 45), (130, 146, 149), (11, 18, 20),
           (42, 82, 83), (174, 127, 44), (70, 84, 89), (182, 239, 209)]
ROUGHNESS = [.58, .78, .40, .91, .57, .62, .48, .55]
METALNESS = [.10, .10, .90, .02, .20, .08, .82, .05]

def png(path, rows):
    def chunk(kind, payload):
        return struct.pack('>I', len(payload)) + kind + payload + struct.pack('>I', zlib.crc32(kind + payload) & 0xffffffff)
    data = b'\x89PNG\r\n\x1a\n'
    data += chunk(b'IHDR', struct.pack('>IIBBBBB', EDGE, EDGE, 8, 2, 0, 0, 0))
    data += chunk(b'IDAT', zlib.compress(b''.join(b'\0' + bytes(row) for row in rows), 9))
    path.write_bytes(data + chunk(b'IEND', b''))

rng = random.Random(7291)
base_rows, orm_rows, normal_rows = [], [], []
for y in range(EDGE):
    br, ore, nr = bytearray(), bytearray(), bytearray()
    for x in range(EDGE):
        tile = (y // 128) * 2 + x // 256
        grain = rng.choice((-1, 0, 0, 0, 1))
        # Broad brushed steel response is roughness only, at two low amplitudes.
        brush = math.sin(y * 1.83) if tile in (2, 6) else 0
        br.extend(max(0, min(255, c + grain)) for c in PALETTE[tile])
        rough = ROUGHNESS[tile] + grain * .004 + brush * .012
        ore.extend((255, round(rough * 255), round(METALNESS[tile] * 255)))
        # Very restrained independent tangent relief. Geometry supplies bevels.
        nr.extend((128 + grain, 128 + (round(brush) if tile in (2, 6) else 0), 255))
    base_rows.append(br); orm_rows.append(ore); normal_rows.append(nr)
for name, rows in [('bastion-basecolor', base_rows), ('bastion-orm', orm_rows), ('bastion-normal', normal_rows)]:
    png(TEXTURES / (name + '.png'), rows)
    subprocess.run(['magick', str(TEXTURES / (name + '.png')), '-define', 'webp:lossless=true',
                    str(TEXTURES / (name + '.webp'))], check=True)

bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
C = Matrix(((1, 0, 0), (0, 0, -1), (0, 1, 0)))
CI = C.inverted()
def xyz(p):
    return C @ Vector(p)
def game(p):
    return CI @ Vector(p)
def srgb(values):
    return tuple(v / 255 / 12.92 if v / 255 <= .04045 else ((v / 255 + .055) / 1.055) ** 2.4 for v in values)

surface = bpy.data.materials.new('Meridian Bastion / original swatch PBR')
surface.use_nodes = True
nodes, links = surface.node_tree.nodes, surface.node_tree.links
bs = nodes.get('Principled BSDF')
def image_node(name, data=False):
    node = nodes.new('ShaderNodeTexImage')
    node.image = bpy.data.images.load(str(TEXTURES / (name + '.png')), check_existing=True)
    if data:
        node.image.colorspace_settings.name = 'Non-Color'
    return node
base = image_node('bastion-basecolor')
orm = image_node('bastion-orm', True)
normal = image_node('bastion-normal', True)
split = nodes.new('ShaderNodeSeparateColor')
links.new(orm.outputs['Color'], split.inputs['Color'])
links.new(split.outputs['Green'], bs.inputs['Roughness'])
links.new(split.outputs['Blue'], bs.inputs['Metallic'])
nmap = nodes.new('ShaderNodeNormalMap')
nmap.inputs['Strength'].default_value = .35
links.new(normal.outputs['Color'], nmap.inputs['Color'])
links.new(nmap.outputs['Normal'], bs.inputs['Normal'])
# AO is a bounded original vertex bake, independent of base-colour light response.
col = nodes.new('ShaderNodeVertexColor'); col.layer_name = 'Col'
mix = nodes.new('ShaderNodeMix'); mix.data_type = 'RGBA'; mix.blend_type = 'MULTIPLY'
mix.inputs['Factor'].default_value = 1
links.new(base.outputs['Color'], mix.inputs[6]); links.new(col.outputs['Color'], mix.inputs[7])
links.new(mix.outputs[2], bs.inputs['Base Color'])

def glow_material(name, rgb, strength):
    m = bpy.data.materials.new(name); m.use_nodes = True
    p = m.node_tree.nodes.get('Principled BSDF'); colour = (*srgb(rgb), 1)
    p.inputs['Base Color'].default_value = colour
    p.inputs['Emission Color'].default_value = colour
    p.inputs['Emission Strength'].default_value = strength
    p.inputs['Roughness'].default_value = .5
    return m
mint = glow_material('Bastion / powered mint', (182, 239, 209), 1.3)
amber = glow_material('Bastion / service amber', (219, 164, 68), .65)
MATERIALS = [surface, mint, amber]
PARTS = []


def empty(name, parent=None, position=(0, 0, 0)):
    obj = bpy.data.objects.new(name, None)
    bpy.context.collection.objects.link(obj); obj.parent = parent; obj.location = xyz(position)
    return obj
root = empty('Bastion')
root['manufacturer'] = 'Meridian Shipworks'; root['assetRole'] = 'station-defense-battery'
root['units'] = 'metres'; root['up'] = '+Y'; root['bore'] = '-Z'
fixed = empty('Bastion_Base', root)
yaw = empty(LAYOUT['yawNode'], root)
yaw['axis'] = '+Y'; yaw['yawUnlimited'] = True
pitch = empty(LAYOUT['pitchNode'], yaw, LAYOUT['pitchPivot'])
pitch['axis'] = '+X'; pitch['pitchMin'] = -.20; pitch['pitchMax'] = math.pi / 2
recoil_roots = {}
for suffix, x in [('Port', -4.2), ('Starboard', 4.2)]:
    rec = empty('Bastion_Recoil_' + suffix, pitch)
    rec['axis'] = '+Z'; rec['rest'] = 0.0; rec['maximumTravel'] = .6
    rec['muzzleCompanion'] = 'Bastion_Muzzle_' + suffix
    recoil_roots[suffix] = rec
    muzzle = empty('Bastion_Muzzle_' + suffix, pitch, (x, 0, -29))
    muzzle['bore'] = '-Z'; muzzle['recoilCompanion'] = rec.name
    muzzle['restPosition'] = [x, 0, -29]


def stock(name, verts, faces, parent, tile=0, bevel=0, material=0, smooth_radial=None, joint=None):
    mesh = bpy.data.meshes.new(name + ' geometry')
    mesh.from_pydata([xyz(v) for v in verts], [], faces); mesh.update()
    bm = bmesh.new(); bm.from_mesh(mesh)
    bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
    if bevel:
        bmesh.ops.bevel(bm, geom=list(bm.edges), offset=bevel, segments=1,
                       affect='EDGES', clamp_overlap=True)
    bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
    bm.to_mesh(mesh); bm.free(); mesh.update()
    obj = bpy.data.objects.new(name, mesh); bpy.context.collection.objects.link(obj); obj.parent = parent
    obj.data.materials.append(MATERIALS[material]); obj['component'] = name
    if joint:
        obj['intentionalJoint'] = joint
    # All material islands stay well inside one swatch. Purposeful macro seams,
    # ridges and edge relief are geometry, not a stretched photographic atlas.
    uv = mesh.uv_layers.new(name='UVMap')
    for poly in mesh.polygons:
        axes = sorted(range(3), key=lambda i: abs(poly.normal[i]))[:2]
        positions = [mesh.vertices[mesh.loops[li].vertex_index].co for li in poly.loop_indices]
        lo = [min(p[a] for p in positions) for a in axes]
        hi = [max(p[a] for p in positions) for a in axes]
        for li in poly.loop_indices:
            p = mesh.vertices[mesh.loops[li].vertex_index].co
            u, v = [(p[a]-lo[j])/max(1e-7, hi[j]-lo[j]) for j, a in enumerate(axes)]
            uv.data[li].uv = ((tile % 2 + .035 + u * .93)/2,
                              (3-tile // 2 + .035 + v * .93)/4)
    if smooth_radial:
        # Explicit radial side / flat cap normals avoid the old rounded-end rod
        # artefact. Shape changes and bevel breaks retain authored face normals.
        origin, axis, radius = smooth_radial
        axis, origin = xyz(axis).normalized(), xyz(origin)
        normals = []
        for poly in mesh.polygons:
            axial = abs(poly.normal.dot(axis))
            for li in poly.loop_indices:
                p = mesh.vertices[mesh.loops[li].vertex_index].co - origin
                radial = p-axis*p.dot(axis)
                normals.append((radial.normalized() if axial < .02 and radial.length > 1e-8 else poly.normal).copy())
            poly.use_smooth = True
        mesh.normals_split_custom_set(normals)
    points = [Vector(v) for v in verts]
    PARTS.append({'object': obj, 'name': name, 'parent': parent.name, 'tile': tile, 'material': material,
                  'joint': joint, 'min': [min(p[i] for p in points) for i in range(3)],
                  'max': [max(p[i] for p in points) for i in range(3)]})
    return obj


def box(name, center, size, parent, tile=0, bevel=.06, material=0, joint=None):
    a,b,c = (n/2 for n in size)
    verts = [(center[0]+x,center[1]+y,center[2]+z) for x in (-a,a) for y in (-b,b) for z in (-c,c)]
    faces = [(0,1,3,2),(4,6,7,5),(0,4,5,1),(2,3,7,6),(0,2,6,4),(1,5,7,3)]
    return stock(name,verts,faces,parent,tile,min(bevel,min(size)*.22),material,joint=joint)


def profile_y(name, levels, sides, parent, tile=0, angle=0, x=0, z=0):
    verts = [(x+r*math.cos(angle+i*math.tau/sides),y,z+r*math.sin(angle+i*math.tau/sides))
             for y,r in levels for i in range(sides)]
    faces = [tuple(reversed(range(sides))),tuple((len(levels)-1)*sides+i for i in range(sides))]
    for j in range(len(levels)-1):
        for i in range(sides):
            a=j*sides+i;b=j*sides+(i+1)%sides
            faces.append((a,b,b+sides,a+sides))
    return stock(name,verts,faces,parent,tile)


def tube(name, center, inner, outer, length, parent, tile=2, sides=16, axis='Z', material=0, joint=None, relief_y=None):
    verts=[]
    if relief_y is not None:
        assert axis=='Z' and sides%4==0 and inner<relief_y<outer
    for i in range(sides):
        a=i*math.tau/sides
        # Two machined meridian reliefs allow the outboard return plungers to
        # translate past this guide; retain the full load-bearing side radius.
        outside=relief_y if relief_y is not None and abs(math.cos(a))<1e-8 else outer
        for q,r in [(-length/2,inner),(-length/2,outside),(length/2,inner),(length/2,outside)]:
            v=(math.cos(a)*r,math.sin(a)*r,q)
            if axis=='Y':v=(v[0],v[2],v[1])
            elif axis=='X':v=(v[2],v[0],v[1])
            verts.append(tuple(Vector(v)+Vector(center)))
    faces=[]
    for i in range(sides):
        a=i*4;b=((i+1)%sides)*4
        faces += [(a,a+1,b+1,b),(a+2,b+2,b+3,a+3),(a,b,b+2,a+2),(a+1,a+3,b+3,b+1)]
    return stock(name,verts,faces,parent,tile,material=material,joint=joint)


def rod(name, a, b, radius, parent, tile=2, sides=10, material=0, joint=None):
    a,b=Vector(a),Vector(b);direction=(b-a).normalized()
    side=direction.cross(Vector((0,1,0)))
    if side.length<.01:side=direction.cross(Vector((1,0,0)))
    side.normalize();up=direction.cross(side).normalized()
    verts=[]
    for end in (a,b):
        for i in range(sides):
            verts.append(tuple(end+radius*(math.cos(i*math.tau/sides)*side+math.sin(i*math.tau/sides)*up)))
    faces=[tuple(reversed(range(sides))),tuple(sides+i for i in range(sides))]
    for i in range(sides):faces.append((i,(i+1)%sides,(i+1)%sides+sides,i+sides))
    return stock(name,verts,faces,parent,tile,material=material,
                 smooth_radial=(tuple(a),tuple(direction),radius),joint=joint)


def cheek(name, side, parent):
    # Raked, tapered forged fork; the inner face stays outside the pitch skin.
    yz=[(4.5,-3.5),(5.0,-4.0),(10.9,-1.2),(11.55,.4),(10.95,2.7),(5.0,5.0),(4.5,4.5)]
    verts=[(side*x,y,z) for x in (6.60,8.55) for y,z in yz]
    n=len(yz);faces=[tuple(reversed(range(n))),tuple(n+i for i in range(n))]
    for i in range(n):faces.append((i,(i+1)%n,(i+1)%n+n,i+n))
    return stock(name,verts,faces,parent,0,.13)


# Fixed interface: octagonal load spreader, continuous annular bearing/seal, four
# supported power/cooling junctions. Every fixed vertex stays inside 20×4×20m.
profile_y('Octagonal foundation armour',[(0,9.45),(.23,10),(.95,10),(1.18,9.60)],8,fixed,1)
profile_y('Foundation upper plate',[(1.15,8.9),(1.38,8.7)],12,fixed,0)
tube('Bearing outer housing',(0,2.57,0),6.80,8.2,2.32,fixed,1,24,'Y')
tube('Bearing lower exposed race',(0,1.52,0),6.72,8.36,.27,fixed,2,24,'Y')
tube('Bearing crown armour',(0,3.72,0),6.78,8.30,.56,fixed,0,24,'Y')
tube('Bearing crown split line',(0,3.34,0),6.77,8.24,.10,fixed,3,24,'Y')
for i in range(12):
    a=i*math.tau/12; x,z=9.03*math.cos(a),9.03*math.sin(a)
    rod('Foundation stud %02d'%i,(x,.97,z),(x,1.16,z),.19,fixed,2,6)
for side in (-1,1):
    for z in (-5.25,5.25):
        x=side*6.35
        box('Fixed junction shroud %s %s'%(side,z),(x,1.47,z),(2.3,.82,2.1),fixed,4,.12)
        box('Junction warning inset %s %s'%(side,z),(x,1.896,z),(1.25,.06,.28),fixed,5,0)
        rod('Power feed A %s %s'%(side,z),(x,1.68,z),(side*5.70,2.18,z*.82),.16,fixed,2)
        rod('Power feed B %s %s'%(side,z),(x+side*.44,1.62,z),(side*6.10,2.20,z*.82),.12,fixed,3)
    # The inner face overlaps the actual 24-sided housing even at the Z ends.
    box('Base service indicator %s'%side,(side*8.15,2.69,0),(.12,.12,1.45),fixed,7,0,1)

# Continuous yaw carrier and fork. Spindle sits inside the fixed bearing with a
# radial service gap; broad top plate actually supports each fork foot.
profile_y('Rotary spindle',[(1.40,6.60),(3.88,6.60),(4.10,6.40)],24,yaw,2)
profile_y('Fork load plate',[(4.03,8.25),(4.28,8.72),(4.82,8.72),(5.0,8.25)],12,yaw,1)
for side in (-1,1):
    cheek('Forged fork cheek '+str(side),side,yaw)
    box('Fork outer service panel '+str(side),(side*8.61,7.05,.4),(.18,3.25,2.75),yaw,4,.09)
    for z in (-.43,1.23):
        box('Fork panel seam %s %s'%(side,z),(side*8.72,7.12,z),(.04,2.40,.055),yaw,3,0)
    tube('Fixed trunnion journal '+str(side),(side*7.35,9,0),.50,1.64,2.30,yaw,2,16,'X',joint='pitch-trunnion')
    tube('Trunnion outer lock '+str(side),(side*8.61,9,0),.36,1.19,.27,yaw,1,16,'X')
    # Shaft enters the forged cheek; the exposed cap must not float in the bore.
    rod('Trunnion center pin '+str(side),(side*8.36,9,0),(side*8.82,9,0),.32,yaw,2,10)
    box('Pitch travel caution '+str(side),(side*8.72,9.30,0),(.05,.19,1.22),yaw,5,0)
# Rear transverse brace avoids the pitch sweep, whose local rear limit is <4.8m.
box('Rear fork cross tie',(0,4.80,6.0),(14.2,.66,1.28),yaw,2,.10)
for side in (-1,1):
    rod('Rear load diagonal '+str(side),(side*6.95,5.0,5.1),(side*4.40,4.60,6.0),.24,yaw,1,8)

# Elevating breeches: paired cassettes, central bridge and a short aft thermal
# manifold. All coordinates below are LOCAL TO PITCH, not station-global.
box('Breech cross bridge',(0,-.85,-.65),(11.8,1.36,6.85),pitch,1,.17)
box('Central power spine',(0,.82,-.20),(2.50,2.38,6.00),pitch,4,.19)
box('Spine ivory shoulder',(0,2.10,-.1),(2.25,.44,5.45),pitch,0,.13)
box('Aft thermal manifold',(0,.10,3.05),(8.9,2.75,.62),pitch,2,.11)
box('Aft heat exchanger inset',(0,.15,3.385),(7.55,1.62,.075),pitch,3,.014)
for i in range(8):
    x=-3.30+i*.943
    box('Aft radiator fin %02d'%i,(x,.15,3.52),(.14,1.43,.29),pitch,2,.025)
for side in (-1,1):
    x=side*4.2
    box('Armoured breech '+str(side),(x,.0,-1.04),(3.95,4.10,8.72),pitch,0,.27)
    box('Breech cap return '+str(side),(x,.10,3.24),(3.38,3.39,.27),pitch,4,.075)
    box('Breech top access '+str(side),(x,2.08,-.8),(2.62,.16,4.8),pitch,4,.065)
    for z in (-2.8,1.15):
        box('Breech access seam %s %s'%(side,z),(x,2.172,z),(2.55,.025,.07),pitch,3,0)
    # Journal only mates at its intended cylindrical contact; the outer cheek
    # skin itself is separated from every rotating receiver vertex.
    tube('Rotating trunnion sleeve '+str(side),(side*6.12,0,0),.50,1.55,.44,pitch,2,16,'X',joint='pitch-trunnion')
    tube('Receiver nose socket '+str(side),(x,0,-6.40),1.75,2.04,2.0,pitch,1,16,joint='barrel-slide',relief_y=1.84)
    tube('Receiver front guide '+str(side),(x,0,-7.47),1.745,2.12,.22,pitch,2,16,joint='barrel-slide',relief_y=1.84)
    # Return cylinders are part of the elevating cradle. Their smaller polished
    # plungers disappear into the cylinder on recoil rather than floating free.
    for dy in (-1,1):
        y=dy*2.02
        tube('Recoil cylinder %s %s'%(side,dy),(x,y,-5.75),.16,.25,4.5,pitch,1,12)
        tube('Recoil gland %s %s'%(side,dy),(x,y,-8.0),.15,.30,.24,pitch,2,12,joint='recoil-plunger')
    box('Breech caution band '+str(side),(x,2.069,1.80),(1.90,.055,.21),pitch,5,0)
    box('Breech ready lamp '+str(side),(x,2.174,.95),(1.10,.045,.10),pitch,7,0,1)

# Actual moving barrels. Hollow profiled tube has one continuous inside wall and
# a large 2.16m clear mouth; there is no disk or luminous cap across the bore.
for suffix,side in [('Port',-1),('Starboard',1)]:
    parent=recoil_roots[suffix];x=side*4.2
    levels=[(-6.00,1.70),(-8.90,1.70),(-9.24,1.46),(-17.20,1.46),(-17.60,1.24),
            (-24.00,1.24),(-24.36,1.52),(-26.45,1.52),(-26.96,1.85),(-28.68,1.85),(-29.0,1.60)]
    n=20;verts=[]
    for z,r in levels:
        for i in range(n):
            a=i*math.tau/n;verts.append((x+r*math.cos(a),r*math.sin(a),z))
    for z in (levels[0][0],levels[-1][0]):
        for i in range(n):
            a=i*math.tau/n;verts.append((x+1.08*math.cos(a),1.08*math.sin(a),z))
    faces=[]
    for j in range(len(levels)-1):
        for i in range(n):
            a=j*n+i;b=j*n+(i+1)%n;faces.append((a,b,b+n,a+n))
    inner0=len(levels)*n;inner1=inner0+n
    for i in range(n):
        j=(i+1)%n
        faces += [(inner0+i,inner0+j,inner1+j,inner1+i),
                  (i,inner0+i,inner0+j,j),
                  ((len(levels)-1)*n+i,(len(levels)-1)*n+j,inner1+j,inner1+i)]
    stock('Hollow tapered barrel '+suffix,verts,faces,parent,2)
    # Dark mid-section and subtle forward muzzle armour form distinct load zones.
    tube('Long barrel dark jacket '+suffix,(x,0,-13.1),1.455,1.49,6.9,parent,1,16)
    tube('Forward service collar '+suffix,(x,0,-24.87),1.51,1.57,.66,parent,4,16)
    tube('Inner emitter annulus '+suffix,(x,0,-28.38),1.035,1.09,.085,parent,7,12,material=1)
    # Structural saddles visibly meet the barrel; cooling rails and return rods
    # are attached to those saddles. They do not extend into the open mouth.
    for z,r in [(-10.0,1.47),(-18.65,1.255)]:
        tube('Cooling saddle %s %s'%(suffix,z),(x,0,z),r-.012,r+.16,.52,parent,0,16)
    for dy in (-1,1):
        rod('Return polished plunger %s %s'%(suffix,dy),(x,dy*2.02,-7.70),(x,dy*2.02,-10.0),.14,parent,2,12,joint='recoil-plunger')
        box('Plunger saddle lug %s %s'%(suffix,dy),(x,dy*1.75,-10.0),(.53,.73,.66),parent,1,.075)
    for dx in (-1,1):
        # Two slightly outboard rigid coolant rails; section supports establish a
        # mechanical connection at each end rather than decorative floating pipes.
        rod('Coolant rail %s %s'%(suffix,dx),(x+dx*1.22,.95,-10.0),(x+dx*1.03,.91,-18.65),.135,parent,6,10)
        for z,cx,cy in [(-10.0,x+dx*1.22,.95),(-18.65,x+dx*1.03,.91)]:
            box('Rail saddle clamp %s %s %s'%(suffix,dx,z),(cx,cy,z),(.33,.33,.39),parent,2,.035)
    # Muzzle flats carry two recessed access bands; no false firing aperture.
    for dy in (-1,1):
        box('Muzzle service flat %s %s'%(suffix,dy),(x,dy*1.840,-27.75),(1.00,.16,1.06),parent,4,.035)
        box('Muzzle caution index %s %s'%(suffix,dy),(x,dy*1.9285,-27.7),(.47,.027,.17),parent,5,0)

# Add a deliberately small original Meridian mark as geometric strokes. Text uses
# an installed deterministic font only when available; typography is decorative,
# not fake live operational status. Keep it on a supported outward aft face.
font_path = Path('/usr/share/fonts/Adwaita/AdwaitaSans-Regular.ttf')
if font_path.exists():
    font = bpy.data.fonts.load(str(font_path))
    def label(name,text,location,size,parent):
        curve=bpy.data.curves.new(name,'FONT');curve.body=text;curve.size=size;curve.align_x='CENTER';curve.align_y='CENTER'
        curve.font=font;curve.extrude=0;curve.resolution_u=2
        obj=bpy.data.objects.new(name,curve);bpy.context.collection.objects.link(obj);obj.parent=parent;obj.location=xyz(location)
        # Front of text is Blender +Z; game +Z = Blender -Y. Exact upright aft face.
        obj.rotation_euler=(math.pi/2,0,0)
        curve.materials.append(surface)
        bpy.ops.object.select_all(action='DESELECT');obj.select_set(True);bpy.context.view_layer.objects.active=obj
        bpy.ops.object.convert(target='MESH')
        mesh=obj.data
        # Converted fonts already own a UV layer. Write the material's active
        # map rather than silently creating TEXCOORD_1 that it never samples.
        uv=mesh.uv_layers[0] if mesh.uv_layers else mesh.uv_layers.new(name='UVMap')
        uv.name='UVMap';uv.active_render=True;mesh.uv_layers.active_index=0
        for li in range(len(mesh.loops)):uv.data[li].uv=(.25,.125)
        PARTS.append({'object':obj,'name':name,'parent':parent.name,'tile':6,'material':0,'joint':None,
                      'min':None,'max':None})
    # Aft plate is at z3.385; fins sit above and below the small central data panel.
    # Keep the identifier on the individual aft breech cap rather than the fins.
    label('Bastion model engraving','BASTION',(-4.2,.22,3.377),.39,pitch)
    label('Meridian maker engraving','MERIDIAN',(4.2,.22,3.377),.29,pitch)

bpy.context.view_layer.update()
# Ambient occlusion is measured on actual assembly triangles in the rest pose.
# Only surface vertices receive a subtle capped contact term; metallic response
# remains separate. Two hemisphere probes avoid scene lights or an albedo bake.
all_verts=[];all_faces=[]
for p in PARTS:
    o=p['object'];o.data.calc_loop_triangles();off=len(all_verts)
    all_verts.extend(o.matrix_world@v.co for v in o.data.vertices)
    all_faces.extend(tuple(off+i for i in t.vertices) for t in o.data.loop_triangles)
ao_tree=BVHTree.FromPolygons(all_verts,all_faces,all_triangles=True)
for p in PARTS:
    obj=p['object'];mesh=obj.data
    if p['material']!=0:continue
    attribute=mesh.color_attributes.new(name='Col',type='FLOAT_COLOR',domain='CORNER')
    rot=obj.matrix_world.to_3x3()
    for poly in mesh.polygons:
        n=(rot@poly.normal).normalized()
        tangent=n.cross(Vector((0,0,1)))
        if tangent.length<.01:tangent=n.cross(Vector((1,0,0)))
        tangent.normalize()
        for li in poly.loop_indices:
            point=obj.matrix_world@mesh.vertices[mesh.loops[li].vertex_index].co+n*.015
            visible=0
            for raydir in (n,(n+tangent*.45).normalized()):
                hit=ao_tree.ray_cast(point,raydir,1.4)
                visible += 1 if hit[0] is None else .70+.30*hit[3]/1.4
            shade=visible/2
            attribute.data[li].color=(shade,shade,shade,1)

# Retain editable component source before constructing disposable export batches.
for image in bpy.data.images:
    if image.source=='FILE':
        image.pack()
bpy.ops.wm.save_as_mainfile(filepath=str(SOURCE/'station-defense.blend'))

# Export batching preserves DOFs and companion names. Individual source pieces
# stay in the .blend; no batch combines base, yaw, pitch or the two recoil paths.
roots=[fixed,yaw,pitch,*recoil_roots.values()]
export_meshes=[]
for parent in roots:
    for material in range(len(MATERIALS)):
        members=[p['object'] for p in PARTS if p['object'].parent==parent and p['material']==material]
        if not members:continue
        copies=[]
        for obj in members:
            copy=obj.copy();copy.data=obj.data.copy();bpy.context.collection.objects.link(copy);copies.append(copy)
        bpy.ops.object.select_all(action='DESELECT')
        for obj in copies:obj.select_set(True)
        bpy.context.view_layer.objects.active=copies[0]
        bpy.ops.object.join();batch=copies[0]
        batch.name=parent.name+('_PBR' if material==0 else '_Powered' if material==1 else '_Amber')
        export_meshes.append(batch)
bpy.ops.object.select_all(action='DESELECT')
for obj in [root,fixed,yaw,pitch,*recoil_roots.values(),*export_meshes]:obj.select_set(True)
for muzzle in LAYOUT['muzzles']:bpy.data.objects[muzzle['node']].select_set(True)
bpy.ops.export_scene.gltf(filepath=str(OUT),export_format='GLB',use_selection=True,
                          export_yup=True,export_apply=True,export_extras=True,
                          export_normals=True,export_texcoords=True,export_tangents=False,
                          export_materials='EXPORT',export_image_format='AUTO')

# Native exporter images are replaced with lossless WebP, then only referenced
# buffer views are retained. No hosted codec or runtime library is introduced.
def load_glb(data):
    length=struct.unpack_from('<I',data,12)[0]
    j=json.loads(data[20:20+length]);binary=data[28+length:]
    return j,binary
j,binary=load_glb(OUT.read_bytes());binary=bytearray(binary)
# Contact AO needs eight-bit precision, not three float32 channels per corner.
# Use standard normalized RGBA8 (opaque alpha) with four-byte vertex alignment.
# This changes no position, normal, UV, index or original lossless texture data.
colour_accessors={p['attributes']['COLOR_0'] for mesh in j['meshes'] for p in mesh['primitives']
                  if 'COLOR_0' in p['attributes']}
colour_packing={'format':'normalized RGBA8','vertices':0,'sourceBytes':0,'packedBytes':0,'maxChannelError':0.0}
for index in sorted(colour_accessors):
    accessor=j['accessors'][index]
    assert accessor['componentType']==5126 and accessor['type'] in ('VEC3','VEC4')
    components=int(accessor['type'][-1]);view=j['bufferViews'][accessor['bufferView']]
    stride=view.get('byteStride',components*4)
    start=view.get('byteOffset',0)+accessor.get('byteOffset',0)
    colour_bytes=bytearray()
    for row in range(accessor['count']):
        values=struct.unpack_from('<'+'f'*components,binary,start+row*stride)
        assert all(0 <= value <= 1 for value in values), 'AO outside normalized colour range'
        quantized=[round(value*255) for value in values]
        colour_packing['maxChannelError']=max(colour_packing['maxChannelError'],
                                               max(abs(value-q/255) for value,q in zip(values,quantized)))
        if components==3:quantized.append(255)
        colour_bytes.extend(quantized)
    while len(binary)%4:binary.append(0)
    accessor['bufferView']=len(j['bufferViews'])
    accessor.update(componentType=5121,type='VEC4',normalized=True)
    for field in ('byteOffset','min','max'):accessor.pop(field,None)
    j['bufferViews'].append({'buffer':0,'byteOffset':len(binary),'byteLength':len(colour_bytes),'target':34962})
    binary.extend(colour_bytes)
    colour_packing['vertices']+=accessor['count']
    colour_packing['sourceBytes']+=accessor['count']*components*4
    colour_packing['packedBytes']+=len(colour_bytes)
assert colour_packing['maxChannelError'] <= 1/510+1e-8
texture_records=[]
for image in j.get('images',[]):
    bv=j['bufferViews'][image['bufferView']];start=bv.get('byteOffset',0)
    payload=bytes(binary[start:start+bv['byteLength']])
    with tempfile.TemporaryDirectory(prefix='bastion-pack-') as tmp:
        source=Path(tmp)/'source.png';target=Path(tmp)/'packed.webp';source.write_bytes(payload)
        subprocess.run(['magick',str(source),'-define','webp:lossless=true',str(target)],check=True)
        packed=target.read_bytes()
    while len(binary)%4:binary.append(0)
    image['bufferView']=len(j['bufferViews']);image['mimeType']='image/webp'
    j['bufferViews'].append({'buffer':0,'byteOffset':len(binary),'byteLength':len(packed)});binary.extend(packed)
    texture_records.append({'name':image.get('name',''),'bytes':len(packed),'sha256':hashlib.sha256(packed).hexdigest(),
                            'width':EDGE,'height':EDGE,'format':'lossless WebP'})
for texture in j.get('textures',[]):
    index=texture.pop('source',None)
    if index is not None:texture.setdefault('extensions',{})['EXT_texture_webp']={'source':index}
for field in ('extensionsUsed','extensionsRequired'):
    if 'EXT_texture_webp' not in j.setdefault(field,[]):j[field].append('EXT_texture_webp')
needed={a['bufferView'] for a in j['accessors'] if 'bufferView' in a}
needed.update(i['bufferView'] for i in j.get('images',[]))
packed=bytearray();views=[];mapping={}
for old in sorted(needed):
    view=j['bufferViews'][old];start=view.get('byteOffset',0)
    while len(packed)%4:packed.append(0)
    mapping[old]=len(views);views.append({**view,'byteOffset':len(packed)})
    packed.extend(binary[start:start+view['byteLength']])
for a in j['accessors']:
    if 'bufferView' in a:a['bufferView']=mapping[a['bufferView']]
for im in j.get('images',[]):im['bufferView']=mapping[im['bufferView']]
j['bufferViews']=views
while len(packed)%4:packed.append(0)
j['buffers'][0]['byteLength']=len(packed)
data=json.dumps(j,separators=(',',':')).encode();data+=b' '*((-len(data))%4)
OUT.write_bytes(struct.pack('<III',0x46546c67,2,28+len(data)+len(packed))+
                struct.pack('<II',len(data),0x4e4f534a)+data+
                struct.pack('<II',len(packed),0x004e4942)+packed)

# Measured source/rest bounds and exact export counts; motion clearance is a
# separate actual-triangle audit, not inferred from an object bounding box.
bpy.context.view_layer.update()
def bounds(objects):
    pts=[game(o.matrix_world@v.co) for o in objects for v in o.data.vertices]
    return {'min':[min(p[i] for p in pts) for i in range(3)],'max':[max(p[i] for p in pts) for i in range(3)]}
manifest={'name':LAYOUT['name'],'stage':'authored export; independent visual and game review pending',
          'builder':'blender/build_station_defense.py','source':'assets/station-defense/station-defense.blend',
          'asset':'public/models/station-defense.glb','units':'metres','up':'+Y','forward':'-Z',
          'layoutSha256':hashlib.sha256(LAYOUT_BYTES).hexdigest(),'blenderVersion':bpy.app.version_string,
          'triangles':sum(j['accessors'][p['indices']]['count']//3 for m in j['meshes'] for p in m['primitives']),
          'bytes':OUT.stat().st_size,'sha256':hashlib.sha256(OUT.read_bytes()).hexdigest(),
          'meshPrimitives':sum(len(m['primitives']) for m in j['meshes']),
          'meshes':len(j['meshes']),'nodes':len(j['nodes']),'materials':len(j.get('materials',[])),
          'bounds':bounds([p['object'] for p in PARTS]),
          'baseBounds':bounds([p['object'] for p in PARTS if p['object'].parent==fixed]),
          'textures':texture_records,'textureDecodedBytesEstimateRGBA8WithMips':sum(EDGE*EDGE*4*4//3 for _ in texture_records),
          'vertexColorPacking':colour_packing,
          'pitchLimits':[-.20,math.pi/2],'yawUnlimited':True,'recoilTravel':[0,.6],
          'recoilContract':'Translate Recoil_{side} local +Z and its direct Pitch-child Muzzle_{side} local Z by the same offset. Both rest at zero offset. No baked clip or gameplay strike authority.',
          'namedNodes':{n['name']:{k:n[k] for k in ('translation','rotation','scale','children') if k in n}
                        for n in j['nodes'] if n.get('name') in ['Bastion','Bastion_Base','Bastion_Yaw','Bastion_Pitch','Bastion_Recoil_Port','Bastion_Recoil_Starboard','Bastion_Muzzle_Port','Bastion_Muzzle_Starboard']},
          'components':[{k:v for k,v in p.items() if k!='object'} for p in PARTS],
          'validation':{'sourceExport':'PASS','motionClearance':'PENDING actual triangle sweep','nativePBR':'PENDING','actualGame':'PENDING','independentArt':'PENDING','performance':'PENDING'}}
assert manifest['triangles']<=LAYOUT['budget']['triangles'],f"Triangle budget exceeded: {manifest['triangles']}"
assert manifest['bytes']<=LAYOUT['budget']['bytes'],f"Byte budget exceeded: {manifest['bytes']}"
for i in range(3):
    assert manifest['baseBounds']['min'][i]>=LAYOUT['baseBounds']['min'][i]-1e-5
    assert manifest['baseBounds']['max'][i]<=LAYOUT['baseBounds']['max'][i]+1e-5
assert LAYOUT_PATH.read_bytes()==LAYOUT_BYTES,'Shared layout changed during authoring'
(SOURCE/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
provenance={'source':'Original deterministic procedural PBR swatches and authored Blender geometry; no external imagery, generated model or hosted service',
            'authoringSession':'Codex / root/kestrel_reviewer, Bastion author role (not its independent reviewer)',
            'paletteReference':'Original Meridian fleet language documented in QUALITY.md and assets/ship-weapons; no copied map payload',
            'builder':'blender/build_station_defense.py','seed':7291,'textureSize':[EDGE,EDGE],
            'baseColorSpace':'sRGB','normalSpace':'OpenGL tangent +Y; non-colour data','ormSpace':'linear; R=1, G=roughness, B=metalness; contact AO is separate vertex colour',
            'normalStrength':.35,'font':'Adwaita Sans, system font; optional decorative engraving only',
            'files':{p.name:{'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size} for p in sorted(TEXTURES.glob('*')) if p.suffix in ('.png','.webp')}}
(TEXTURES/'provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
print('BASTION_EXPORTED '+json.dumps({k:manifest[k] for k in ('sha256','bytes','triangles','meshPrimitives','bounds','baseBounds')}))
